### ISSUE TITLE
wandb-cli run command not showing all runs in a project

### ISSUE THREAD

**Issue by umgupta** [wandb/client#1038]
* Weights and Biases version: 0.8.36
* Python version: 3.6.9
* Operating System: Linux

### Description
Trying to list all projects in a run

### What I Did

```
wandb runs -p <project-name>
```
The command was successful but listed only the first 10 projects in the run. Ideally, I would expect to list all runs or have a parameter to configure how many runs I want to see.

**Comment by cvphelps** [comment]
Hi there Umang, here's the API for querying multiple runs: https://docs.wandb.com/library/api#querying-multiple-runs

**Comment by umgupta** [comment]
@cvphelps Yes, I can use api for that. But wouldn't it be better to just provide a parameter (`-n` for example) to let user query last `n` runs. Writing python code for just querying runs is a bit too much, isn't it? Also, documentation is a bit confusing on this as it doesn't say it would only list the last 10 runs. 

Perhaps this is not a bug but consider this as a feature request. If this is something desirable, I would be happy to contribute and add this flexibility else feel free to close this.

**Comment by ariG23498** [comment]
Hey @umgupta 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by nbren12** [comment]
I am +1 for building a CLI to query runs to avoid context switching from the terminal to web console and also since the web ui can be challenging to navigate at times (esp when layering groups, filters etc). Would it be best to open a new issue?

We have some code [here](https://github.com/ai2cm/fv3net/blob/ec51280035833164870d43ae44773dbeaf71ca41/projects/microphysics/scripts/query-wandb.py) that does this already, but obviously an official CLI would be better. One example usage is like this:
```
$ query-wandb.py runs --group combined-gscond-dense-local-v2-v1 --job-type piggy
combined-gscond-dense-local-v2-v1-online piggy-back cool-shape-3938 https://wandb.ai/ai2cm/microphysics-emulation/runs/3t7bhsyx
combined-gscond-dense-local-v2-v1-offline piggy-back azure-galaxy-3936 https://wandb.ai/ai2cm/microphysics-emulation/runs/1sgufb9k
```
