### ISSUE TITLE
WandB incorrectly recognising transformers import as PyTorch (should be dynamic to PT or TF)

### ISSUE THREAD

**Issue by DMells** [wandb/client#1214]
* Weights and Biases version: 0.9.5
* Python version: 3.6
* Operating System: MacOS

### Description
Using colab, I was trying to run a sweep on a tf.keras model, the embeddings for which were created using huggingface's transformers tokenizer.

However, on import of transformers, WandB by default assumes you want to run a PyTorch model (checked by calling `wandb.config.as_dict()`, and so when running the sweep, despite the outputs showing correct setup, nothing happens after the links to the various project pages/runs are posted in the console output. 

### What I Did
```
!pip install transformers
!pip install wandb

import transformers
import wandb

!wandb login

wandb.init()
wandb.config.as_dict()
> {'_wandb': {'desc': None,
  'value': {'cli_version': '0.9.5',
   'framework': 'torch',
   'huggingface_version': '3.0.2',
   'is_jupyter_run': True,
   'is_kaggle_kernel': False,
   'python_version': '3.6.9'}}}
```

A workaround for now is to load a separate colab workbook, convert the inputs to embeddings as normal using the Huggingface tokenizer, but then save the embeddings as a numpy array to your colab directory.

In your other wandb notebook, don't import transformers, just load the saved embeddings. On doing this, `wandb.config.as_dict()` gives 'framework: 'tensorflow', and the sweep runs as expected.

**Comment by raubitsj** [comment]
FYI: the _wandb structure in the config dictionary is just for internal telemetry and no actions of the script or library should be taken based on its values.   We use a very simple heuristic right now to determine framework and will be enhancing it soon to better reflect the "primary" framework used, rather than just what modules are loaded.

I am not sure about the behavior in the huggingface integration based on modules loaded -- but it shouldnt have to do with our fuzzy platform detection.

**Comment by vanpelt** [comment]
@borisdayma any ideas on what might be happening here?

**Comment by DMells** [comment]
@raubitsj thanks that would explain why when trying to manually amend the config dictionary 'framework' value there was no effect.

**Comment by borisdayma** [comment]
`transformers` detects the presence of `wandb` and will automatically logs runs if you use `Trainer` or `TfTrainer`.

You can disable this functionality with `os.environ['WANDB_DISABLED']="true"` (which should be suggested to you in the print output). This will desactivate it only for `transformers`.

@raubitsj @vanpelt The issue may be related to the `transformers` library automatically calling `wandb.init` at [this line](https://github.com/huggingface/transformers/blob/05e7150a53cc6c1571c0e3acb1b4d692737976d9/src/transformers/trainer.py#L472), which in colab will do a reinit which is why nothing is displayed in the sweeps.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
