### ISSUE TITLE
wandb local - endless "change password" loop

### ISSUE THREAD

**Issue by cgebbe** [wandb/client#1219]
wandb, version 0.9.4 (installed via conda)
Python 3.7.7
Linux

### Description

- Setup wandb according to quickstart
- wandb local
- Opened http://localhost:8080/home
- The screen pops up with "Change Password: Enter a new password for the account associated with local@wandb.com"
- I enter a password
- The same "Change Password" screen appears again...

### What I Did

- I can actually just ignore it and click the wandb logo in the top left to see my projects etc...
- However, when I want to access the linked tensorboard, the same "change password" screen pops up and I cannot ignore it any longer

### More information

- Top right button > Users > Teams reveals the following setup
- row1: {Team name: xyz, Members: local}
- row2: {Team name: wandb, Members: <empty>}

Probably something stupid, but don't know how to fix it and haven't found an existing thread

**Comment by cvphelps** [comment]
Thanks for reporting this, adding to our eng backlog to examine further

**Comment by vanpelt** [comment]
Hey @cgebbe when the instance boots we prompt you to create an admin account.  I think the issue is you've created an admin account with the email `local@wandb.com` which is a reserved name.  The easiest fix would be to create a new admin account and remove the `local@wandb.com` from the user management UI.  It would be easiest for me to hop on a screenshare to fix with you.  Can you email at vanpelt@wandb.com to setup a quick screenshare?

**Comment by cgebbe** [comment]
Hi @vanpelt , sorry for the late reply. I believe I simply left the email empty at the beginning, so your guessed cause seems very likely. I'll check this evening and report back if I can't fix it myself.

**Comment by MassimilianoBiancucci** [comment]
I got the same issue and I found this workaround, you can delete the docker volume, and when the docker image is restarted you can create another user.

the list of commands:

docker stop wandb-local
docker volume ls # to check the volume name
docker volume rm wandb # delete the wandb volume
wandb local # now you can create another user
