### ISSUE TITLE
TextStream not handling carriage returns

### ISSUE THREAD

**Issue by vanpelt** [wandb/client#135]
`output.log` in the run dir isn't handling carriage returns.  Using any keras example in the examples repo reproduces it.  Let's spend some more time trying to get to the bottom of it.

**Comment by adrianbg** [comment]
By" handling carriage returns", do you mean performing the same compression
that the back end does? That's expected at the moment.

**Comment by vanpelt** [comment]
I just mean that `output.log` on the local file system should respect the carriage returns and go back to the beginning of the line.

**Comment by adrianbg** [comment]
Yeah the current behaviour is expected (ie. it's not that something is
broken, just that I didn't have time to do it another way yet). What you're
talking about is a specific example of terminal emulation. The way the
backend does it seems to be good enough for now but it's also pretty
flawed. Carriage returns don't actually erase lines.

On Feb 25, 2018 5:34 PM, "Chris Van Pelt" <notifications@github.com> wrote:

I just mean that output.log on the local file system should respect the
carriage returns and go back to the beginning of the line.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/wandb/client/issues/135#issuecomment-368366212>, or mute
the thread

**Comment by vanpelt** [comment]
Understood, you would think a bunch of other folks are doing this in the CI world.  I definitely wouldn't start from my implementation 🌵

**Comment by adrianbg** [comment]
Hmm yeah I'm sure there's some good code out there. PTYs are terminal
emulators provided by the operating system. They can be set take care of
the processing you're talking about, but I'd prefer to use a Python
implementation for a few reasons.

Another option is to store the entire byte stream of the output so people
can go back and forth in time if they want to, or at least to avoid
throwing away the intermediate terminal data. Catting an output.log in a
terminal should do the right thing with carriage returns.
