### ISSUE TITLE
Logs not syncing when wandb-history.jsonl is quite large.

### ISSUE THREAD

**Issue by nsidn98** [wandb/client#1357]
When I run `wandb sync wandb/my_run` the history metrics are not uploaded to the wandboard. It just stays like that till I kill the command with Ctrl+C.

The folder `wandb/my_run` contains the following contents:
```

2.4K  config.yaml
402K  model.ckpt
9.6M  output.log
748K  wandb-events.jsonl
62M  wandb-history.jsonl
16B  wandb-metadata.json
61K  wandb-summary.json
```

The output I get after running `wandb sync wandb/my_run`:
```
wandb: Syncing wandb/my_run to:
wandb: exp_name https://app.wandb.ai/usr_name/project_name/runs/hash
wandb: Uploading history metrics
```
and after that it does not progress.

Does wandb sync have limits in upload sizes.

**Comment by tyomhak** [comment]
Hey @nsidn98 , are you sure that it's stuck? or maybe it just takes a long time to upload the data?

@shawnlewis are there size limits?

**Comment by nsidn98** [comment]
I kept it running for an hour or so and it still did not work. But if I remove the 62MB `wandb-history.jsonl` file and sync it, then it happens almost instantaneously. So I guess the latency is because of the 62MB file.

**Comment by vanpelt** [comment]
You're running a rather old version of the library.  In the latest version we store all data in a much more efficient format.  Unfortunately you can not sync old run directories with this new version.  I believe we added some performance fixes to `wandb sync` in the later version of the 0.9.x series.  What version are you currently using (wandb --version)?  If it's less than `0.9.7` you can sync try syncing this directory with the latest old version by running `pip install wandb==0.9.7`.  Moving forward you should upgrade your library to the 0.10.x series by running `pip install wandb --upgrade`.  Just note you can only sync runs tracked with 0.10.x using 0.10.x and <= 0.9.x with the 0.9.x series.

**Comment by nsidn98** [comment]
My current wandb version is `0.9.6`. Do you mean that I need to upgrade my wandb first to `0.9.7` and then sync my directories. And then possibly try to upgrade to the latest version(0.10.x) for future experiments?

**Comment by vanpelt** [comment]
Correct, although I think 0.9.6 had the performance fix I mentioned so I'm not sure 0.9.7 will fix the sync issue.  A sure fire way to fix the sync issue is to remove histograms or other large structures from `wandb-history.jsonl`.  You can use a program named [jq](https://stedolan.github.io/jq/download/) to do this.  The example below takes all history rows with "gradients/" in the name and removes them:

```
cat wandb-history.jsonl | jq -c 'with_entries(if (.key|test("gradients/.")) then empty else ( {key: .key, value: .value } ) end )' > wandb-history-simple.jsonl
```

**Comment by nsidn98** [comment]
Although it worked with `jq`, is it possible to not remove the "gradients/" row from the logs and sync them?

**Comment by vanpelt** [comment]
I think if you run the sync with all the data it will eventually finish, just might take 5-10 minutes assuming you have enough ram.  For runs logged with 0.10.x and greater, this shouldn't be an issue.

**Comment by nsidn98** [comment]
The sync did not finish even after running the sync command for an hour or so. It just stops at `wandb: Updating run and uploading files` without moving forward to the progress bar for the uploads.

**Comment by vanpelt** [comment]
Bummer, I've confirmed the "fix" I had for uploading large files was added in 0.9.5.  The relevant code that's causing issue is here:

https://github.com/wandb/client/blob/v0.9.7/wandb/apis/file_stream.py#L251

You could modify your local installation of wandb to see what's going on there.  Another thing to try would be just hard-coding the lines_per_request to something like 2 or 10.  The root cause is likely trying to send too much data to the backend at once.  Adding a print statement to the while loop would let you see how much progress it's able to make.  You can find the local path to your wandb install by opening a python console and running:

```
import wandb
print(wandb.__path__)
```

**Comment by nsidn98** [comment]
The problem still persists even after upgrading wandb to 0.10.5. The command is stuck with the following output:
`Syncing: https://wandb.ai/usr_name/project_name/runs/wcq98 ...`

My system has 8GB RAM and I rand the same experiment as earlier with the latest version of wandb.

**Comment by vanpelt** [comment]
Can you share one of the problem run directories with us?  My email is vanpelt@wandb.com if it's easier to send a zip or tarball there.

**Comment by nsidn98** [comment]
Have sent the folder as a google drive link on your email id.

**Comment by nsidn98** [comment]
Any update on this? I have been uploading my runs without the gradient and weight parameters using `jq` to monitor the training but I need them to debug the training procedure.

**Comment by vanpelt** [comment]
Hey @nsidn98 I haven't had a chance to look at the historic run.  Have you switched to using the latest release of wandb (0.10.7) for new training?  I *believe this issue is only present for runs logged with the 0.9.x series.  Also, why are you running sync after training, is there a specific reason you can't have the runs just log directly to the wandb server during training?

**Comment by nsidn98** [comment]
The logs I sent you were with wandb 0.10.5. The reason for running sync after training is that the cluster on which I am running my experiments on gets disconnected from the internet while running jobs for safety purposes. And hence I have to `scp` them to my local machine and then sync the runs.

**Comment by vanpelt** [comment]
Great, I've got meeting all afternoon, but I'll look at this tonight and get back to you.

**Comment by vanpelt** [comment]
Hey @nsidn98 I was able to finally sync the run.  The issue seemed to be due to a very large number of lines with carriage returns.  My current fix is not without issues.  For reasons not yet clear to me the single histogram that was logged to this run is not getting synced.  You can install from my branch with: 

```
pip install --upgrade git+git://github.com/wandb/client.git@bug/sync#egg=wandb
```

This will at least get the bulk of the data synced.  I'll keep investigating the missing histograms.

**Comment by nsidn98** [comment]
This is working well now with large file sizes. Thanks a lot!
