### ISSUE TITLE
Wrong int cast for min and max values of parameters

### ISSUE THREAD

**Issue by carloalbertobarbano** [wandb/client#1421]
I have the following yaml configuration for some parameters:

```
beta:
    min: 0.0
    max: 1.0
```

However, when generating a new sweep with the wandb CLI they are casted to int. From the web interface I can see

```
beta:
   min: 0
   max: 1
```

And so the values are sampled from an integer distribution, instead of a float uniform. Is this a bug or am I missing something?

**Comment by tyomhak** [comment]
hey @carloalbertobarbano, I think this might be a bug. Can you share the link to this sweep? My mail is artyom@wandb.com

meanwhile as a workaround you could manually set the distribution to be float uniform, as described in the docs [here](https://docs.wandb.com/sweeps/configuration#parameters).

**Comment by carloalbertobarbano** [comment]
Unfortunately it is a private project, but it should be easily reproducible. Meanwhile, I will explicitly specify the distribution type, thanks for the feedback!

**Comment by mwalton** [comment]
I'm having this issue as well. It's not hard to address once you catch it, but I think it's worth looking into as it's easy to miss when configuring large sweeps and breaks many optimisation tasks which are naturally defined this way. Two public sweeps illustrating this:

Demonstration of the issue: [int cast issue sweep](https://wandb.ai/mwalton/solver_sandbox/sweeps/vynkplxk) which occurs when using the following in a sweep config:
```
ya:
    min: 0.0
    max: 2.0
```

[Expected behaviour](https://wandb.ai/mwalton/solver_sandbox/sweeps/dotpo2ga) (using a workaround)

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by julianStreibel** [comment]
Same issue.

**Comment by diegochine** [comment]
Still having the issue. Any float parameter with no digits after the dot (like 1.0, 5.0, 10.0) is casted to int.
