### ISSUE TITLE
Custom Charts: Export Panel Feature

### ISSUE THREAD

**Issue by alexmirrington** [wandb/client#1446]
**Description:**

I would love to see the ability to export custom charts from the web UI.

**Details:**

I imagine the implementation would be similar to the export functionality of existing charts. At the very least, I would like to see PNG exports at various resolutions. Currently, I have to take a screenshot of the chart at its native browser resolution in order to put it in a latex report. If possible, SVG exports that capture a static view of the chart would be excellent.

**Comment by tyomhak** [comment]
Hey @alexmirrington , thanks for the feature request! I'm filing an internal ticket for this feature.

**Comment by sydholl** [comment]
Hi @alexmirrington, we wanted to let you know you can export custom charts. Please let us know if you have any other questions!

**Comment by xhlulu** [comment]
@sydholl I tried exporting an SVG file from W&B to overleaf. I encountered two issues:
* `\includesvg` will give an error and fail to display, although it works with other types of SVG files
* The file size is ~6MB even for a simple plot. if i include multiple plot the latex file size will become unreasonably large.
* PDF is accepted in latex, but PDF export doesn't work in W&B
* PNG is not a convenient export format since high DPI makes the file very large, and low DPI will look blurry when you zoom in.

Right now the only alternative would be to log the data offline and use `plotly.express` to generate & export the charts to SVG. Would love to keep using W&B in order to customize the graphs in the UI before exporting.

**Comment by xhlulu** [comment]
@sydholl To reproduce this, please try using the overleaf template from [the answer in this thread](https://tex.stackexchange.com/questions/442077/is-it-possible-to-use-svg-images-with-overleaf) and replace the svg with something exported from wandb: ![wandb_chart](https://user-images.githubusercontent.com/21180505/152408705-a3b47923-ec64-47b4-b240-af43caf91d1f.svg)

**Comment by AntonioLopardo** [comment]
Any updates on this? I'm having issues importing in overleaf too. @xhluca Did you find a good solution or are you just using pdfs?

**Comment by xhluca** [comment]
I'm exporting the data and using plotly.express. i only use wandb for logging data.

**Comment by AbhiKhoyani** [comment]
@xhluca can you tell me how to export logged data, I'm able to export only summary data from wandb-summary.json file from artifact but not other logged data.
