### ISSUE TITLE
Display labels on the x axis

### ISSUE THREAD

**Issue by astariul-colanim** [wandb/client#1542]
I'm trying to display a simple bar chart with labels being on the x-axis, but I can't find the way to do it.

I do the following :

```python
import wandb

wandb.init(project="test")
data = [["label1", 46], ["label2", 32], ["labelX", 35.5]]
table = wandb.Table(data=data, columns=["label", "value"])
wandb.log({'my_histogram': wandb.plot.bar(table, "value", "label", title="title")})
```

But the displayed chart is empty :

![image](https://user-images.githubusercontent.com/43774355/100070799-b1942d80-2e7d-11eb-9889-bfffd75fe5a2.png)

---

If I change and put the labels on the y-axis, it works perfectly :

```python
wandb.log({'my_histogram': wandb.plot.bar(table, "label", "value", title="title")})
```

![image](https://user-images.githubusercontent.com/43774355/100070903-cf619280-2e7d-11eb-8b99-7ff613600ac8.png)

---

**How can I put the labels on the x-axis ?**

**Comment by staceysv** [comment]
Thanks for using custom charts! The default histogram called via `wandb.plot.bar` uses horizontal bars. It sounds like you're looking for a chart with vertical bars. The easiest way to change the bar orientation is to edit the definition of the chart.
I wrote a report to describe this use case which you may find helpful: [how to extend a custom preset](https://wandb.ai/wandb/plots/reports/Extend-a-Preset-Histogram-Bins--VmlldzozMTAxMjU).

You can start with any instance of the horizontal-bar chart, then hover over the top right corner and click the pencil icon to edit. You'll see the chart definition in [Vega](vega.github.io), which you can edit. Here's an example from my [report on bar charts](https://wandb.ai/wandb/plots/reports/Custom-Bar-Charts--VmlldzoyNzExNzk):
![Screen Shot 2020-11-24 at 8 40 16 AM](https://user-images.githubusercontent.com/45573465/100125075-39a01600-2e31-11eb-996e-f1ac91607fee.png)
from here, if you swap the "x" and the "y" under encoding (lines 15 and 20 for me, may be a bit different for you), you will get a vertical bar chart:
![Screen Shot 2020-11-24 at 8 41 02 AM](https://user-images.githubusercontent.com/45573465/100125302-7b30c100-2e31-11eb-923a-ca7c6d94f034.png)

You can use the menu in the top right to save this as a preset (e.g. "vertical_bar_chart") and reuse it in your work. You can reuse it by changing each logged chart instance (via wandb.plot.bar) from the dropdown via the UI, or you can log to your new chart directly from python by calling something like this:
```python
data = [["label1", 46], ["label2", 32], ["labelX", 35.5]]
table = wandb.Table(data=data, columns=["label", "value"])
fields = {"value" : "value",  "title" : "Your title here"}
custom_bar_chart = wandb.plot_table(
    vega_spec_name="[your wandb username]/vertical_bar_chart",
    data_table = table,
    fields = fields)
wandb.log({"my_histogram" : custom_bar_chart})
```
Note: if you want to set the title like this from Python, right now you'll also need to modify the title field. It's on line 7 in my examples above, and `"title": "${string:title}"` to `"title": "${field:title}"` will do the trick. This tells W&B to expect the title as a field from the `fields` dictionary instead of as a string from the UI.

Hope this helps, let me know if you have any more questions!

**Comment by astariul-colanim** [comment]
@staceysv, that's exactly what I wanted !

Thank you for the very detailed answer. I read the doc, but I didn't understand I can save Vega config and reuse it in Python.

Your answer clarified everything :)
