### ISSUE TITLE
float32 numbers in wandb.Table get displayed with full precision even when rounded

### ISSUE THREAD

**Issue by jklaise** [wandb/client#1598]
**Describe the bug**
When logging a `pandas` dataframe that has `float32` columns via `wandb.Table`, the dashboard expands the numbers to full precision even if the numbers have been rounded to a few decimal places for display purposes. This does not happen if the `dtype` is `float64`.

**To Reproduce**
```python
import pandas as pd
df = pd.DataFrame({'col1': np.round(np.random.rand(100), 2).astype(np.float32)}) # bug does not happen for the default np.float64
wandb.log({'test': wandb.Table(dataframe=df)})
```

**Expected behavior**
Rounding on the dashboard is respected for `float32` numbers just as it is for `float64` numbers.

**Screenshots**
With `float32`:
![2020-12-10-17:30:02](https://user-images.githubusercontent.com/13080878/101808061-c1fb0800-3b0d-11eb-9f63-9f0def47a6f4.png)

With `float64`:
![2020-12-10-17:35:28](https://user-images.githubusercontent.com/13080878/101808398-3170f780-3b0e-11eb-83be-9a808d90de97.png)

**Operating System**
 - OS: Arch Linux
 - Browser: Chromium
 - Version: 0.10.11

**Comment by ariG23498** [comment]
Hey @jklaise 
Thanks for the ticket
I can reproduce your issue and it does seem to be a problem

## Code
```python
import wandb
import pandas as pd
import numpy as np
df32 = pd.DataFrame({'col32': np.round(np.random.rand(10), 2).astype(np.float32)})
print(df32)
df64 = pd.DataFrame({'col64': np.round(np.random.rand(10), 2).astype(np.float64)})
print(df64)
df = pd.concat([df32, df64], join = 'outer', axis = 1) 
print(df)
wandb.init(entity="xxx", project="xxx")
wandb.log({'test': wandb.Table(dataframe=df)})
wandb.finish()
```

## Screenshots
### Terminal
![image](https://user-images.githubusercontent.com/36856589/101863338-7726d200-3b99-11eb-8187-287f974068bd.png)
_The numbers are rounded to two decimal places_

### Wandb
![image](https://user-images.githubusercontent.com/36856589/101863010-4a72ba80-3b99-11eb-82c1-5d821294335f.png)
_The `float32` does not seem to be rounded_

**Comment by tssweeney** [comment]
Hello @jklaise thank you for the report. I looked into this and would like to share some learnings.

Numpy’s float32 is lower precision than python’s internal float (64) representation. So when the float32 is eventually materialized, it is cast to a float, resulting in the tailing garbage. This is a canonical floating point issue. The reason that the dataframe printout shows a rounded float32 is because it is using the string representation which does it's best to approximate the precision when converting to a string. Showing just numpy see here:

```
import numpy as np
for n in [0.1, 0.123456789123456789]:
    print("\nn:      ", n)
    
    n32 = np.float32(n)
    n64 = np.float64(n)
    
    print("n32:    ", n32.item(), "\t", str(n32))
    print("n64:    ", n64.item(), "\t",str(n64))
    print("64(32): ", np.float64(n32.item()), "\t",np.float64(str(n32)))
```

Results in:

```
n:       0.1
n32:     0.10000000149011612     0.1
n64:     0.1     0.1
64(32):  0.10000000149011612     0.1

n:       0.12345678912345678
n32:     0.12345679104328156     0.12345679
n64:     0.12345678912345678     0.12345678912345678
64(32):  0.12345679104328156     0.12345679
```
As you can see, the .item() call which is documented as the recommended method to extract underlying data from numpy is yielding precision errors. However, calling str() gives the expected result.

In the PR above, I began "hacking" together a patch that would check for float32s and attempt to make the float32 -> str -> float conversion. However, as you might imagine, this is flakey and not reliable. While it seems to work for raw numpy arrays, pandas is a bit more difficult. From what I can tell, pandas makes the conversion to float64 immediately under the hood and there is no way to extract a value without loosing precision or gettin the garbage.

Ultimately, I would recommend sticking with float64 for these purposes - is that an option for you? Please let me know - happy to continue the discussion.

Regards,
Tim

**Comment by jklaise** [comment]
@tssweeney that's some nice detective work!

It's not a big issue for me to cast to `float64` before logging, but I think this step should be reflected in the documentation as it's not obvious what is happening and how to fix it. I think this may come up quite often as with deep learning the tensors are almost always `float32` and when converting to `numpy` or `pandas` users would hit the same issue without the explicit casting.
