### ISSUE TITLE
scan_history does not efficiently retrieve sparse metrics

### ISSUE THREAD

**Issue by cswinter** [wandb/client#1680]
**Describe the bug**

Calling `scan_history` returns the very first data point but doesn't seem to make any subsequent progress.
Script seems to be stuck in wandb networking code, sample stacktrace:

```
Thread 1494 (idle): "MainThread"
    read (ssl.py:911)
    recv_into (ssl.py:1052)
    readinto (socket.py:589)
    _read_status (http/client.py:257)
    begin (http/client.py:296)
    getresponse (http/client.py:1321)
    _make_request (urllib3/connectionpool.py:383)
    urlopen (urllib3/connectionpool.py:603)
    send (requests/adapters.py:449)
    send (requests/sessions.py:646)
    request (requests/sessions.py:533)
    request (requests/api.py:60)
    post (requests/api.py:116)
    execute (gql/transport/requests.py:38)
    _get_result (gql/client.py:60)
    execute (gql/client.py:52)
    execute (wandb/apis/public.py:178)
    __call__ (wandb/old/retry.py:96)
    wrapped_fn (wandb/old/retry.py:132)
    _load_next (wandb/apis/public.py:2002)
    __call__ (wandb/old/retry.py:96)
    wrapped_fn (wandb/old/retry.py:132)
    wrapper (wandb/apis/normalize.py:24)
    __next__ (wandb/apis/public.py:1975)
    fetch_run_data (plot_results.py:15)
    <module> (plot_results.py:23)
```

The run I'm trying to download has a very large number of data points, but the requested metric is present in only 26 rows and the run page has now trouble loading it.

**To Reproduce**

My code:

```python
import wandb
from typing import Tuple

def fetch_run_data(descriptor: str, metric: str) -> Tuple[np.array, np.array]:
    api = wandb.Api()
    runs = api.runs("cswinter/deep-codecraft-vs", {"config.descriptor": descriptor})

    run = runs[0]
    step = []
    value = []
    vals = run.scan_history(keys=[metric, '_step'], page_size=1000, min_step=None, max_step=None)
    for entry in vals:
        if metric in entry:
            print('yay')
            print(entry)
            step.append(entry['_step'])
            value.append(entry[metric])
    return np.array(step), np.array(value)

frames, step = fetch_run_data("f2034f-hpsetstandard", "eval_mean_score")

# plot data...
```

It just outputs this and then hangs for at least several minutes:

```
yay
{'eval_mean_score': -0.9901801347732544, '_step': 0}
```

**Expected behavior**
I expect the full set of data points to be retrieved within seconds.

**Operating System**
WSL 1
wandb==0.10.12

**Comment by cswinter** [comment]
After several minutes, it has now downloaded the second data point. I'm assuming the backend (slowly) scans over the entire set of logged values? Is there a more efficient way for me to retrieve the data while guaranteeing no sampling? (run page seems to be able to do it)

One workaround would be for me to spin up a hundred processes to download all the data I need overnight. Is that fine or would it make your backend sad?

**Comment by cswinter** [comment]
Hmm ok, `history` does seem to do what I want when setting the right `keys`. Is it guaranteed to return the full underlying dataset without any sampling/interpolation when settings the `samples` param higher than the number of data points?

**Comment by vanpelt** [comment]
It looks like the issue is the shear volume of data here.  The current non-sampled history method will return all keys, which makes for a lot of bandwidth as well (if you pass `keys=` to scan_history we actually each "page").  Each request shouldn't take more than a few seconds though, I'm looking into the performance issues now.  We rate limit requests to ensure our backend can handle the load, if you ran 100's of processes they would likely stall on rate limits.

The regular history method will randomly sample down to 100k data points if all the keys you're requesting are scalars.  If any of the keys are histograms or other media types we sample down to 10k data points.

On thing to try would be increasing the page_size to 5k in scan_history.  In my tests that made each requests take ~2 seconds, and fewer requests will reduce the chance you're getting rate limited.  I'll do some more digging into the performance here, it's really strange how your script is hanging and I'm still trying to reproduce.

**Comment by vanpelt** [comment]
Hey @cswinter I was able to reproduce the issue.  For especially sparse metrics you should definitely use the regular `history` method.  `scan_history` has to iterate over every step in the run.  Since you have 120 million steps, this is rather expensive.  The only time `history` won't work is if you have > than 10k data points for a specific metric.  The history sampling is smart enough to return all values for a metric if there are fewer than 10k data points.

If you do need to scan the entire history, I suggest increasing the page size to 100k, that will speed things up and reduce the number of api calls you're making.

**Comment by cswinter** [comment]
Makes sense, thanks for the detailed analysis! I've started using the `history` method and it's been working well. I need much less than 10k data points so sounds it should be fine.

**Comment by cswinter** [comment]
Small note: the maximum value of `_step` is about 125 million, but it is actually logged at an interval of 16384 so there should only be around 7630 datapoints which doesn't seem like that many.

**Comment by vanpelt** [comment]
Gotcha, the pagination logic for scanning the entire history needs to assume there could be a data point at every step so it needs to page across the entire 125 million which is what makes it so slow.  We're working on a big overhaul of our metrics backend so hopefully we can address this case better in the future.

**Comment by omniscientoctopus** [comment]
> Small note: the maximum value of _step is about 125 million, but it is actually logged at an interval of 16384 so there should only be around 7630 datapoints which doesn't seem like that many.

 I have a similar query, and I am curious if there is an efficient way to do this now?
