### ISSUE TITLE
Upgrading to 0.10.13  caused runtime error

### ISSUE THREAD

**Issue by Yura32000** [wandb/client#1703]
**Describe the bug**
I updated wandb to the latest version 0.10.13 from 0.10.12
The following line stopped to work properly.
 
wandb.log({'MappingFileDescription/MyDescription': wandb.Table(dataframe=df.describe())}, step=0) 

**To Reproduce**

**Expected behavior**

**Operating System**
 - OS: Ubuntu 18.04
 - Browser chrome

**Comment by ariG23498** [comment]
Hey @Yura32000 
I happen to reproduce the ticket
This is the code that I have used:
```python
# This is to ensure that I have the latest version of wandb
!pip install --upgrade -q wandb

# Imports
import wandb
import pandas as pd
# Emulating the data
data = {
    "A":[1,2,3,4],
    "B":[1,2,3,4],
    "C":[1,2,3,4],
}

df = pd.DataFrame(data)
with wandb.init(entity="xxx", project="xxx") as run:
  run.log({"Description": wandb.Table(dataframe=df.describe())}, step=0)
```

This is what the dashboard looks like :point_down: 
![image](https://user-images.githubusercontent.com/36856589/104742253-37db3a80-5770-11eb-93fe-af648928e7e8.png)

I did not happen to run into any problem whatsoever. Please let me know if I have missed on some details here.

**Comment by Yura32000** [comment]
--> 174     wandb.log({f'Mapping File Description/{caption}': wandb.Table(dataframe=df.describe())}, step=0)
    175 
    176 

~/tf24/lib/python3.6/site-packages/wandb/data_types.py in __init__(self, columns, data, rows, dataframe, dtype, optional)
    513         # Explicit dataframe option
    514         if dataframe is not None:
--> 515             self._init_from_dataframe(dataframe, columns, optional, dtype)
    516         else:
    517             # Expected pattern

~/tf24/lib/python3.6/site-packages/wandb/data_types.py in _init_from_dataframe(self, dataframe, columns, optional, dtype)
    570         self._make_column_types(dtype, optional)
    571         for row in range(len(dataframe)):
--> 572             self.add_data(*tuple(dataframe[col].values[row] for col in self.columns))
    573 
    574     def _make_column_types(self, dtype=None, optional=True):

~/tf24/lib/python3.6/site-packages/wandb/data_types.py in add_data(self, *data)
    635                 )
    636             )
--> 637         self._validate_data(data)
    638         self.data.append(list(data))
    639 

~/tf24/lib/python3.6/site-packages/wandb/data_types.py in _validate_data(self, data)
    647             raise TypeError(
    648                 "Data column contained incompatible types. Expected type {}, found data {}".format(
--> 649                     current_type, incoming_data_dict
    650                 )
    651             )

TypeError: Data column contained incompatible types. Expected type <WBType:dictionary | {'type_map': {'T0': <WBType:union | {'allowed_types': [<WBType:none | {}>, <WBType:object | {'class_name': 'int64'}>]}>}}>, found data {'T0': 5617}

**Comment by Yura32000** [comment]
This is error I get from upgrading 0.10.12 to latest version

**Comment by tssweeney** [comment]
Hi @Yura32000 - hopefully I can help here. 

Firstly, the error is claiming that the data in a particular column is of mixed type (we recently added enforcing a single type in a column). Specifically, it is saying that it got an np.int64, followed by a the value 5617 (which I suspect is a python int, or perhaps an np.int32). In any case, I agree that it is a bug as the second value should be able to be cast to the first. 

I cannot validate this hypothesis since when I call `df.describe()`, I get columns of all the same type. Is it possible to share exactly what you get when you do `df.describe()` and `df.describe().dtypes`, that would be helpful (also your pandas version). 

In any case, assuming this hypothesis is correct, you have two workaround options:
1. Cast your "describe frame" to force homogenous columns. In the following example I use `float` since that is what I would expect `describe` to return, but you can also try `int` if that makes sense for your use case: `...wandb.Table(dataframe=df.describe().astype(float)...`
2. If that does not work, then there is a bug in the type validation logic. In that case, you can disable the type checking using a "private" API. Note that this API subject to change (indicated by the underscore), but will disable type checking so you can keep doing your experiments: `...wandb.Table(dataframe=df.describe(), dtype=wandb.sdk.interface._dtypes.AnyType)...`

Note: I am still puzzled as to why there seems to be different types coming out of `df.describe()`. But hopefully this unblocks you for the time being. Thank you for your bug report and patience.

**Comment by Yura32000** [comment]
172 def wandb_log_mapping_file(df, caption):
    173     wandb.log({f'Mapping File/{caption}': wandb.Table(dataframe=df)}, step=0)
--> 174     wandb.log({f'Mapping File Description/{caption}': wandb.Table(dataframe=df.describe(), dtype=wandb.sdk.interface._dtypes.AnyType)}, step=0)
    175 
    176 

AttributeError: module 'wandb.sdk.interface' has no attribute '_dtypes'

**Comment by Yura32000** [comment]
The fix still doesn't work

**Comment by tssweeney** [comment]
@Yura32000 - apologies for the wrong import pattern. You should be able to say:
```
from wandb.sdk.interface._dtypes import AnyType
# then later on...
wandb.Table(..., dtype=AnyType)
```

I just validated this locally.

**Comment by Yura32000** [comment]
Thanks it works now

**Comment by jacobdanovitch** [comment]
I was having this issue when trying to log a dataframe of strings that had some NaNs. I tried `.fillna('')` and now I'm just getting this:

![image](https://user-images.githubusercontent.com/17260949/106175850-963aec80-6164-11eb-9298-7c58049a2b4d.png)

Not sure what the issue is.
