### ISSUE TITLE
[CLI] api.run returns dataframe with missing rows

### ISSUE THREAD

**Issue by mwalton** [wandb/client#1783]
I'm finding that multiple calls to api.run inexplicably return dataframes where some steps are dropped (appears to only occur at the start of the df. eg:

```
api = wandb.Api()
calla = api.run("<entity>/<project>/<run_id>").history()
callb = api.run("<entity>/<project>/<run_id>").history()
```
example (first row dropped):
![image](https://user-images.githubusercontent.com/1017968/106442734-ecb56d00-647b-11eb-8bd0-119c2381c68b.png)

**Comment by ariG23498** [comment]
Hey @mwalton 
Thanks for the issue here
Could you help us with a reproducible code snippet here? We could also do with the knowledge of the particular `entity/project/run_id` configuration that you have used.

I have checked this on my machine and the `dataframe` seems to be fine for both the calls. I am tagging a not-reproduced tag here for the time being.

**Comment by vanpelt** [comment]
Hey @mwalton `history()` returns a sampled history for performance reasons.  If you want the full history you should use `scan_history()`.

**Comment by mwalton** [comment]
thanks guys! @ariG23498 I wasn't able to reproduce the same behaviour I was seeing on my dataset using the entity/project/run_id you indicated; however @vanpelt 's suggestion addressed my use case. If it's of interest or useful, I could make the particular run I was having issues public so you could reproduce. I'll close for now as using `scan_history()` works. thanks again!
