### ISSUE TITLE
Able to continue adding data in same Text Table [Feature] 

### ISSUE THREAD

**Issue by aadityachapagain** [wandb/client#1826]
Consider, I have long running Program, which produce billions of logs every day, Its impossible to create table with all data  and feed it to wandb dashboard.

Currently , when I create and log text table in wandb using following methods , 
```
# Method 1
data = [["I love my phone", "1", "1"],["My phone sucks", "0", "-1"]]
wandb.log({"examples": wandb.Table(data=data, columns=["Text", "Predicted Label", "True Label"])})

# Method 2
table = wandb.Table(columns=["Text", "Predicted Label", "True Label"])
table.add_data("I love my phone", "1", "1")
table.add_data("My phone sucks", "0", "-1")
wandb.log({"examples": table})
```

**It will create New table every time I log, rather than continue adding data on already existed table.**

**If we have a functionality of adding data incrementally in already existed table, That would be really really helpful.**

Thanks

**Comment by tyomhak** [comment]
Hi @aadityachapagain , thank you for the request. I'm sharing this request with the team. Also I'll let you know if we have a workaround for this.

**Comment by cvphelps** [comment]
Hi there, we can't support adding new rows to existing tables that you've already logged, but here are two approaches:

1. Keep the wandb.Table locally and add new rows to it. Once you've got all the rows in, call wandb.log
2. Keep logging the same table at each step, and just add new rows to it. the final table you log will have all the rows you want, and you'll be able to see the latest table logged in the UI

**Comment by aadityachapagain** [comment]
Its more like a data Collections over span of certain time ( and yehh it could go over billions of log per week ) , we both have numeric and text data ( numeric as in metrics ). Both are disjointed , so, we can could also log numeric on wandb and text data locally, But since wandb already provide us with nice dashboard. I thought aforementioned feature would be really nice for us . 
Thats all.
So, If requested Feature is possible This would greatly affect our interactions with wandb and make everything easy.

**Comment by ariG23498** [comment]
Hey @aadityachapagain 
I would like to close this ticket for the time being.
I will let you know if there is any update on this.
Thanks!

**Comment by miguelvalente** [comment]
Bumping to show interest in the feature.

**Comment by nousr** [comment]
also bumping to show interest.

**Comment by jstmn** [comment]
Bumping as well - this would be very useful for me too! I'm surprised that you aren't able to view tables across different time steps like you can with images, plots, etc.

**Comment by eladn** [comment]
Bumping to show interest! Super relevant to us!

**Comment by sashank-tirumala** [comment]
Bumping to show interest, the current tabular logging is very annoying

**Comment by tchittesh** [comment]
Bumping for a similar use case (I log images in each row, which quickly take too much memory if I'm storing the entire table in memory).

**Comment by simonebonato** [comment]
Showing interest also! Waiting till the end of the training to see the table with the results its quite annoying. I am trying to train a simple seq2seq model with attention for machine translation, and I would love to see some examples as the training runs, but don't want to wait till the end to notice that they are all bad...

**Comment by eohomegrownapps** [comment]
not really a solution, but a workable hack: 
- log one table with name `myTable` every timestep
- join / visualise all tables at once by pasting `runs[0].loggedArtifactVersions.map((row, idx) => row.file("myTable.table.json").))` into the table expression field

**Comment by abhijeet00** [comment]
Also Bumping to show interest.

I am currently training an object detection model, and I was thinking to log random sample data: groundtruth Images, predictions Images and related metadata from validation steps to the wandb table.
 
 Once the wandb table is created, we can't add data incrementally due to which :
1) If I keep the image data in memory till the last epoch, and accumulate all the data to a local wandb table, then incase If I interrupt model training, table will not be logged in wandb dashboard.  

2) If I log the table at each validation step or epoch, I need to first append the rows to the local wandb table, and log the updated table with all the rows again and again in each validation epoch. Its not ideal if I am training model for large number of epochs, as local table will consume more memory.

 I would like to use as much available memory as possible to train larger models and less memory to track the performance of model while visualizing & monitoring the model output as the training runs.

**Comment by scottire** [comment]
@abhijeet00 see this thread: 

> I've given some instructions to overcome this in this thread:
https://github.com/wandb/wandb/issues/2981#issuecomment-1686868189
