### ISSUE TITLE
[Q]can wandb dashboard display Chinese?

### ISSUE THREAD

**Issue by HaoLiuHust** [wandb/client#1898]
I wonder can wandb web UI display Chinese

**Comment by lukas** [comment]
Yes - it should display Chinese anywhere - if you find somewhere that doesn't work please let us know.  We've had a couple unicode issues in the past but I believe they are resolved.

![image](https://user-images.githubusercontent.com/29/109180768-13e02100-7740-11eb-8d3e-0f771c3ed9a8.png)

**Comment by HaoLiuHust** [comment]
What I mean is the menu in wandb, such as "charts" in your image

**Comment by lukas** [comment]
If you click on the three dots on the right you can change the label charts.  We haven't internationalized the app so that everything is automatically translated into Chinese although we are considering it - would that help you?

![image](https://user-images.githubusercontent.com/29/109248122-153e3780-779a-11eb-8f1f-97434914c828.png)
