### ISSUE TITLE
wandb.plots.ROC for multilabel classification

### ISSUE THREAD

**Issue by awsaf49** [wandb/client#1900]
Is there any way to plot `roc curve` for `multilabel classification` using `wandb.plots.ROC` ?
format:
```
y_true = [[0, 1, 1], [1, 0, 1]]
y_pred = [[1, 1, 0], [1, 0, 0]]
```

**Comment by tyomhak** [comment]
Hey @awsaf49 , I'm not quite sure. Let me check with the team regarding this.

**Comment by tssweeney** [comment]
Hi @awsaf49, currently, the `wandb.plots.roc_curve(y_true, y_pred)` expects the following format:
- `y_true` is a sequence of length N, where each entry is a class index
- `y_pred` is a sequence of shape NxC where each row is the class probabilities for each class. 

A simple example would be:
```
y_true = [0,1,2,0,1,2,0,1,2]
y_pred = [
    [0.1, 0.2, 0.0],
    [0.2, 0.4, 0.4],
    [0.3, 0.6, 0.1],
    [0.4, 0.1, 0.5],
    [0.5, 0.1, 0.4],
    [0.1, 0.1, 0.8],
    [0.2, 0.2, 0.6],
    [0.3, 0.4, 0.3],
    [0.4, 0.6, 0.0]
]
```

Since this format does not support multi-class classification today, a workaround would be to simply remap your predictions such that each row corresponds to a single class. Consider this converter function:
```
def convert(multi_true, multi_pred):
    t = []
    p = []
    for i, pred in enumerate(multi_pred):
        for clss in multi_true[i]:
            t.append(clss)
            p.append(pred)
    return t, p
```

In this case `multi_pred` is the same shape as `y_pred` before, but `multi_true` would look something like: `[[0,1],[0,1],[1],[0,1,2],[0],[2],[0,2],[1,2],[2]]` where each entry is a list of classes.

I think this will solve your problem in the short run, and we can log a ticket to support this natively. Please let me know (:

Thanks!
