### ISSUE TITLE
[CLI] Trouble setting up wandb library in Windows path

### ISSUE THREAD

**Issue by Fez3** [wandb/client#1969]
**Description**

pip install wandb installs the package, but the wandb command is not available.
Running 'wandb login' in the command line returns 'bash: wandb: command not found'
Running 'python -m wandb.cli' workaround instead returns "C:\Users\user\Anaconda3\python.exe: No module named wandb.cli.__main__; 'wandb.cli' is a package and cannot be directly executed"
 

 

**Environment**
- OS: Windows
- Environment: Git Bash
- Python Version: 3.8.5

**Comment by ariG23498** [comment]
Hey @Fez3 
I am not sure about the `Git Bash` terminal.
Would you like to try the same commands with a `cmd` prompt?

**Comment by vanpelt** [comment]
I've seen this before when users have run `conda install wandb` instead of `pip install wandb`.  It could be that your python bin directory isn't in your path.  Try to add `C:\Users\user\Anaconda3\bin` to your path as described below:

https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/

**Comment by Fez3** [comment]
The result is the same in cmd: "'wandb' is not recognized as an internal or external command,
operable program or batch file."

I have added the bin directory to path, but nothing has changed

**Comment by farizrahman4u** [comment]
@Fez3 If you did `pip install wandb`, you should add the `Scripts` directory of your python installation to path.
