### ISSUE TITLE
Image widget doesn't work in safari

### ISSUE THREAD

**Issue by vanpelt** [wandb/client#197]
Try this page in Safari, says there are no images:

https://app.wandb.ai/trentwatson1/mask-rcnn/runs/s5b0rasc

Seems to work in Chrome.

**Comment by thekatic** [comment]
@vanpelt As it turns out, problem was not only in Safari. 
Because `history` object is flatten [here](https://github.com/wandb/client/blob/master/wandb/board/ui/src/components/RunViewer.js#L87), method for extracting images didn't work properly.

I applied [quick fix](https://github.com/wandb/client/commit/272f15f65e34ce678c9b51cc3c3c58d4164000ea) in order not to change entire logic, but let me know if you think its a bit hacky.

**Comment by lukas** [comment]
Vlad - that was my fault - I fixed the flatten for you upstream so you don't have to unflatten.

**Comment by thekatic** [comment]
Thanks @lukas
