### ISSUE TITLE
[CLI] Unable to enter API Authorization key in Jupyter notebook

### ISSUE THREAD

**Issue by abdulsam** [wandb/client#1970]
**Description**
I have entered following code in Jupyter notebook cell:

`!pip install --upgrade wandb`
`!wandb login`

The Library is installed and it is asking for my API key like shown in below image.
![Screenshot from 2021-0s3-17 15-06-22](https://user-images.githubusercontent.com/11463868/111448982-f72e7c00-8734-11eb-8d71-fbf1f7aa9fa3.png)

### **Issue**
**_I can't paste my API key there in text-box as annotated by pink brush._**

Environment: Jupyter notebook - version 5.6.0
Python version: 3.7.0
running on: localhost:8888

**Comment by ariG23498** [comment]
Hey @abdulsam 
Thanks for the ticket. We will be tracking it internally.
For the time being some of the workarounds you could do are as follows:
- use `wandb.init()` directly instead of using `wandb login` beforehand. `wandb.init()` fires a similar interface for you to paste the API key (this is working fine).
- use `$wandb login` in a comman line interface and get your self logged in.
- in the code itself, set the `os.environ["WANDB_API_KEY"]=<YOU API KEY>` and execute the cell.

**Comment by vanpelt** [comment]
Inside of jupyter you can call `wandb.login()` and you should be prompted for your api key.  You can also call `wandb.login(key=XXXX)` if you aren't prompted but be careful as that will expose your secret key in the notebook source code which is not secure.
