### ISSUE TITLE
[Q] Sweeping during a dry run wandb.sweep

### ISSUE THREAD

**Issue by roshan-k-patel** [wandb/client#2008]
Hi i'm trying to sweep during a dry run (no internet) and an error keeps being thrown .

The line

 `sweep_id = wandb.sweep(sweep_config, project="basic hyperparam optimisation")`

requests http access. It is used to initialise the sweep with

`wandb.agent(sweep_id, train)`

My environment variables are set and this run works on a computer with internet (just fails as cuda runs out of memory)

os.environ["WANDB_ENTITY"]="rpatel9"
os.environ["WANDB_PROJECT"]="basic hyperparam optimisation"
os.environ["WANDB_MODE"] = "dryrun"

**How do I initialise the sweep to be run offline? I'm using the simpletransformers library**

**Comment by roshan-k-patel** [comment]
![wandb error](https://user-images.githubusercontent.com/48667731/112822576-b29ecb00-90ba-11eb-9142-def3629177ed.PNG)

**Comment by vanpelt** [comment]
Hey @roshan-k-patel you can not run a sweep in offline mode.  Sweeps require access to a central sweep server to calculate the next set of parameters.  You could run a sweep agent on a machine with internet and have that agent launch sweep runs into a cluster without internet.  The other option would be to run a [self hosted ](https://docs.wandb.ai/self-hosted) server.

**Comment by roshan-k-patel** [comment]
Thanks for your reply @vanpelt. I have a few questions:

1.) At the end of the train function i call wandb.finish(), however i noticed some scripts used wandb.join() which is no longer in your documentation. What does join() do and should i be using this instead of finish()?

2.) I am going to try your suggestion of starting the sweep on a machine with internet and have the agent launch sweep runs into a cluster. Would i just replace the whole contents of the train function with an sbatch call to my slurm workload manager? Also, in this case how would wanadb know when the cluster has finished that train function and would i manually sync the local files created after the end of each call? If there's a w&b tutorial for something like this please direct me to it.

3.) Separately, i've been trying to run this on computer with a gtx 2070, which can handle 1 to 2 instances of the model i'm trying to use. But it seems when i use the sweep the agent will initialise a model and initialise multiple more models before the first one has finished, which causes cuda to run out of memory. I think from what i can tell the agent tries to run 3 jobs in parallel as the w&b interface shows 3 new runs at a time. How can i force the agent to only run 1 job at a time so i'm able to finish one run and call torch.cuda.empty_cache() before the next one starts? Here's a screenshot of my terminal output, Thank you!: 

<img width="1792" alt="Screenshot 2021-03-30 at 11 35 04 AM" src="https://user-images.githubusercontent.com/48667731/112933380-51c2d180-9152-11eb-9d07-279f6174e2f9.png">

**Comment by roshan-k-patel** [comment]
Here's my entire script for clarity:

```
# Python ≥3.5 is required
import sys

assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn

assert sklearn.__version__ >= "0.20"

# Common imports
import pandas as pd
import numpy as np
import os

from sklearn.model_selection import train_test_split

import torch
import wandb
import sklearn.metrics
import os

if __name__ == '__main__':
    # api key
    os.environ["WANDB_API_KEY"] = ""

    # user and project id
    os.environ["WANDB_ENTITY"] = "rpatel9"
    os.environ["WANDB_PROJECT"] = "basic hyperparam optimisation"

    # no internet run
    # os.environ["WANDB_MODE"] = "dryrun"

    """
    Data arrangement
    """

    # df_fpb = pd.read_csv("./data/train_set_df_4352.csv")
    df_fpb = pd.read_csv("./data/financial-phrase-bank-v1.0/Sentences_50Agree.txt", sep='@', encoding='latin-1',
                         names=['Text', 'Rating'])

    df_fpb.columns = ['text', 'labels']

    df_fpb = sklearn.utils.shuffle(df_fpb, random_state=42)

    # """Changed the getlabel function in binaryprocessor class to have 3 labels, negative, neutral, positive"""
    df_fpb['labels'] = df_fpb['labels'].replace('negative', 0)
    df_fpb['labels'] = df_fpb['labels'].replace('neutral', 1)
    df_fpb['labels'] = df_fpb['labels'].replace('positive', 2)

    # 80% train, 10% eval, 10% test
    df_train, df_test_val = train_test_split(df_fpb, test_size=0.2, random_state=42)
    df_eval, df_test = train_test_split(df_test_val, test_size=0.5, random_state=42)

    """
    Hyper param optimisation - part 1 
    """

    import logging
    from statistics import mean, mode
    from sklearn.metrics import accuracy_score, f1_score
    from simpletransformers.classification import ClassificationArgs, ClassificationModel

    sweep_config = {
        "name": "vanilla-sweep-batch-16",
        "method": "bayes",
        "metric": {"name": "f1_macro", "goal": "maximize"},
        "parameters": {
            "num_train_epochs": {"min": 1, "max": 40},
            "learning_rate": {"min": 0, "max": 4e-4},
        },
        "early_terminate": {"type": "hyperband", "min_iter": 6, },
    }

    sweep_id = wandb.sweep(sweep_config, project="basic hyperparam optimisation")

    logging.basicConfig(level=logging.INFO)
    transformers_logger = logging.getLogger("transformers")
    transformers_logger.setLevel(logging.WARNING)

    # Preparing train data
    train_df = df_train
    eval_df = df_eval
    test_df = df_test

    model_args = ClassificationArgs()
    model_args.eval_batch_size = 8
    model_args.evaluate_during_training = True
    model_args.evaluate_during_training_silent = False
    model_args.evaluate_during_training_steps = 1000
    model_args.learning_rate = 4e-4
    model_args.manual_seed = 42
    model_args.max_seq_length = 512
    model_args.multiprocessing_chunksize = 5000
    model_args.no_cache = True
    model_args.no_save = True
    model_args.num_train_epochs = 10
    model_args.overwrite_output_dir = True
    model_args.reprocess_input_data = True
    model_args.train_batch_size = 16
    model_args.gradient_accumulation_steps = 2
    model_args.train_custom_parameters_only = False
    model_args.wandb_project = "basic hyperparam optimisation"


    def train():
        # Initialize a new wandb run
        wandb.init()

        # Create a TransformerModel
        model = ClassificationModel(
            "albert",
            "albert-xlarge-v1",
            num_labels=3,
            use_cuda=True,
            args=model_args,
            sweep_config=wandb.config,
        )

        # Train the model
        model.train_model(
            train_df,
            eval_df=eval_df,
            accuracy=sklearn.metrics.accuracy_score,
            f1_macro=lambda truth, predictions: sklearn.metrics.f1_score(truth, predictions, average='macro'),
            f1_weighted=lambda truth, predictions: sklearn.metrics.f1_score(truth, predictions, average='weighted')
        )

        # Finish the run
        wandb.join()
        torch.cuda.empty_cache()


    wandb.agent(sweep_id, train)
```

**Comment by vanpelt** [comment]
> 1.) At the end of the train function i call wandb.finish(), however i noticed some scripts used wandb.join() which is no longer in your documentation. What does join() do and should i be using this instead of finish()?

wandb.finish and wandb.join do the exact same thing.  We're planning to deprecate wandb.join and encourage all users to use wandb.finish moving forward.

2.) I am going to try your suggestion of starting the sweep on a machine with internet and have the agent launch sweep runs into a cluster. Would i just replace the whole contents of the train function with an sbatch call to my slurm workload manager? Also, in this case how would wanadb know when the cluster has finished that train function and would i manually sync the local files created after the end of each call? If there's a w&b tutorial for something like this could you please direct me to it? Or if you'd be able to break it down for me in terms of which commands require internet and how i should break up the script / deploy the agent in terminal / use an sbatch command to queue the train method to be run in my cluster, i would really appreciate that.

You can not use "bayes" or "early_stopping" if your runs aren't reporting their metrics in realtime because the search algorithm won't know what's working and what's not working, "random" will work fine.  In terms of what command should actually be run, you can create a python or bash wrapper script that calls into slurm to schedule jobs.  This script could poll slurm for the status of the job, and automatically download the results and sync them to wandb when a job finishes or fails.  You can customize the command that the command line agent uses in the [sweep configuration](https://docs.wandb.ai/sweeps/configuration#command).

3.) Separately, i've been trying to run this on computer with a gtx 2070, which can handle only 1 instance of the model i'm trying to use during normal runs. But it seems when i start the sweep, the agent will initialise a model and cuda runs out of memory. I think from what i can tell the agent tries to run 3 jobs in parallel as the w&b interface shows 3 new runs at a time. And once it fails keeps trying to initialise in groups of 3. Here's an example, illustrated by the gpu memory allocations:

In general you should run `wandb agent username/project/sweep_id` from the command line on a machine that has internet.  This sweep command can be configured to run your custom python or bash script that calls into slurm and poll's the backend for status.  I would avoid calling `wandb.agent` inside of your python code as that's what could lead to the CUDA oom

**Comment by roshan-k-patel** [comment]
Thank you, so just to clarify a few things:

If using a random or grid search instead of Bayesian, will the sweep work without internet as there's no need to poll the server for parameters?

On your second point does "This script could poll slurm for the status of the job, and automatically download the results and sync them to wandb when a job finishes or fails" qualify as "realtime", and mean a bayes search is viable here or no?

Could you please provide me with a little more info on how this"polling" would work and what aspects of the agent's command i'd have to change? I can't quite get what you mean from reading the documentation. I'm guessing it will be along the lines of a loop that constantly checks if the job is still active, but in what way would one customise the command line agent's command to allow for that?

Does the sweep generally use quite a bit more memory compared to when a model is run without it? I'm just wondering if i can just about load and train a transformer model from hugging face in a jupyter notebook without getting oom, should i expect that it should not run out of memory during the sweep as long as i initialise it properly with the agent command you listed at the end of your response?

Really appreciate your responses!

**Comment by vanpelt** [comment]
> If using a random or grid search instead of Bayesian, will the sweep work without internet as there's no need to poll the server for parameters and it can be initialised completely locally then sync'd at the end?

Correct, random doesn't query a search space that mutates

> On your second point does "This script could poll slurm for the status of the job, and automatically download the results and sync them to wandb when a job finishes or fails" qualify as "realtime", and mean a bayes search is viable here or no?

Bayes should work in this case, but early stopping definitely won't.  If you have multiple agents running in parallel the timing of the search syncing the metrics will impact the bayes search space.

> Could you please provide me with a little more info on how this"polling" would work and what aspects of the agent's command i'd have to change? I can't quite get what you mean from reading the documentation. I'm guessing it will be along the lines of a loop that constantly checks if the job is still active, but in what way would one customise the command line agent's command to allow for that?

Sure, here's a basic example.  Let say you configure your sweep to run a program named slurm.py, there's likely no need to customize the command line in this case.  Your program could look like (psudeo code):

```python
running = None
while True:
  if running is None:
    proc = subprocess.Popen(["slurm", "..."], stdout=subprocess.PIPE)
    code = proc.wait() 
    if code == 0:
      running = proc.stdout.read()
    else:
      raise ValueError("Command failed")
   else:
      status_proc = subprocess.Popen(["slurm", "status", "..."], stdout=subprocess.PIPE)
      if status_proc.wait() == 0:
         print("Still running...", running)
         time.sleep(10)
      else:
         print("Finished running", running)
         sys.exit(0)
```

> Does the sweep generally use quite a bit more memory compared to when a model is run without it? I'm just wondering if i can just about load and train a transformer model from hugging face in a jupyter notebook without getting oom, should i expect that it should not run out of memory during the sweep as long as i initialise it properly with the agent command you listed at the end of your response?

The sweep will only impact the memory of your process if one of the search parameters is connected memory usage.   For instance if one of your hyper parameters was kernel size for your convolutions the higher that number the larger your model will be.  

The OOM you were seeing is likely being caused by running multiple `train` functions in the same process.  The previous call to the `train` function may not of let go of the CUDA memory because those objects haven't been garbage collected.  By running the sweep agent as a process using `wandb agent XXX` from the command line instead of `wandb.agent()` from inside a python environment ensures the memory is freed.  Inside of jupyter you could run `!wandb agent XXX` from a cell and just ensure there's a file with the same name as you specified for the program key of your sweep config in the directory.

**Comment by vanpelt** [comment]
Only runs associated with your sweep are used to determine the next set of parameters.

**Comment by tokaka22** [comment]
Why it looks in wandb offline mode, sweep agent will never end even run through all hyper-parameter combos?

**Comment by LouisSerrano** [comment]
Hi @roshan-k-patel  @vanpelt, I wanted to do something similar and I wanted to know if you were able to make the suggestion work.

**Comment by brando90** [comment]
@vanpelt so how is the recommended way to run a wandb sweep for debugging?

**Comment by brando90** [comment]
https://stackoverflow.com/questions/76585219/what-is-the-official-way-to-run-a-wandb-sweep-with-hugging-face-hf-transformer?noredirect=1#comment135036154_76585219
