### ISSUE TITLE
[Feature] save code for the structure class.

### ISSUE THREAD

**Issue by amssljc** [wandb/client#2104]
**Is your feature request related to a problem? Please describe.**
I've been training a lot of pytorch models in my python project. After 100 or more models have been trained, I need to load and compare the models. However i need to save 100 and even more models class like in my scripts, which is very time consuming and cumbersome.
```
class model_i(nn.Module):
      something...
```
Therefore, if there a method that when I training the `model_i` the system can automatically save my class to a new .py file. By the way, I don't want to save those classes all together, because I may forget the class name or have the same class name for different stucutures in it with even a single activation function changed.

**Describe the solution you'd like**
I know wandb can automatically save the `main.py` , so I want save the structure ,or the model (the code) trained at the same time.

**Comment by ariG23498** [comment]
Hey @amssljc 
One way to solve the issue is with `artifacts`. You can use the `torch.save` to get the `pickle` model and use `wandb.artifact` to save the model. On the other hand you can use `wandb.save` to save the model class which holds the architecture of model as shown.
This way you would not only get the weights of the model, but also the model class that will help you reproduce the inference any time you want.

Does this solution help you?

**Comment by cvphelps** [comment]
@amssljc you can also call wandb.log_code("path/to/your/dir") which will log all the code as artifacts

**Comment by amssljc** [comment]
> @amssljc you can also call wandb.log_code("path/to/your/dir") which will log all the code as artifact

thanks for your reply, but i cant use `wandb.log_code`

This is the traceback:
```
AttributeError: module 'wandb' has no attribute 'log_code'
```

my wandb version: '0.10.27'

**Comment by vanpelt** [comment]
Sorry, it's `wandb.run.log_code(".")`
