### ISSUE TITLE
[App] Allow resume run in sweep

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#2235]
**Describe the bug**
https://docs.wandb.ai/guides/track/advanced/resuming "Note that resuming a run which was executed as part of a Sweep is not supported."

**Comment by dannygoldstein** [comment]
This is now supported as of 0.10.31, please see the docs here: https://docs.wandb.ai/guides/track/advanced/resuming#preemptible-sweeps

**Comment by dreamflasher** [comment]
That's amazing! Now we're looking forward to be able to do good resuming. Even something hacky would be great to work with, I think the basic would be: being able to specify the start step (at which one has a checkpoint) and I guess checkpointing could be hacked around?

**Comment by vanpelt** [comment]
@dreamflasher today when you resume, we'll initialize the step of the logger to the last step reported in the previous run.  We have plans to let you `rewind` that step to the previous checkpoint.  But until then you can use a seperate key in your calls to `wandb.log` with the step instead of the native `step` keyword arg of `wandb.log`.  i.e.

```
wandb.log({"acc": X, "global_step": Y})
```

This should allow you to essentially "rewind" until we formally add that api.
