### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by ashok-arjun** [wandb/client#2240]
**Is your feature request related to a problem? Please describe.**
When I'm working on multiple projects, I would like to use multiple W&B teams/accounts. But the `wandb login client_key` sets the client key globally and does not allow it to change inside directories. 

In contrast, `git` allows having local config files that contain the username and account, which gets recorded for every commit. 

I'd love to see this feature in W&B.

**Describe the solution you'd like**
Instead of setting the client key globally, a local `.wandb` folder can be used to set a local key, just like how `git` does.

**Comment by tyomhak** [comment]
Hey @ashok-arjun , thank you for the request!

**Comment by vanpelt** [comment]
Hey @ashok-arjun if you want to configure multiple teams / account you can use environment variables instead of the `wandb login` command.  Simply set `WANDB_API_KEY` to the account you want to use in your environment and everything will work.  If you're using bash you could create a simple script to update your current shell environment, or you can do it directly in python by setting `os.environ['WANDB_API_KEY'] = XXX`

**Comment by ashok-arjun** [comment]
Thank you for the suggestion @vanpelt.
