### ISSUE TITLE
Wandb never resume after network error resolved [CLI] 

### ISSUE THREAD

**Issue by kevinNejad** [wandb/client#2344]
**Description**
The wandb logging stopped due to the HTTPError (500 Server Error: Internal server error for url ...). However, the network error resolved and "resuming normal operation" was printed out. But the log aren't updated on the web app anymore.

**Wandb features**
I am using PyTorch Lightening, with "ddp" backend. I'm also running my model on a HPC cluster.

**Environment**
- OS: [Linux]
- Python Version: [eg. 3.8.3]

**Comment by vanpelt** [comment]
Hey @kevinNejad which version of the wandb client library were you using?  You can find this with `wandb --version` from the command line, or in the web UI by clicking the Overview icon in the upper left of the run page.

**Comment by kevinNejad** [comment]
@vanpelt thanks for the reply. The wandb version is 0.10.26

**Comment by vanpelt** [comment]
Thanks @kevinNejad.  This was a known issue that we fixed in [0.10.30](https://github.com/wandb/client/blob/master/CHANGELOG.md#01030-may-7-2021).  To prevent this from happening in the future be sure to run `pip install wandb --upgrade` in any environments you're running experiments in.  To fix the specific run that is missing metrics, if you can still access the directory it was run in you can find the run dir in the `wandb` directory relative to your script and run:

```
wandb sync wandb/run-XXX-XXX-XXXX
```

To have the metrics replayed to a server.
