### ISSUE TITLE
[Q] How to disable wandb interface inside google colab during wandb.init()?

### ISSUE THREAD

**Issue by forkbabu** [wandb/client#2410]

**Comment by vanpelt** [comment]
```
%env WANDB_MODE=disabled
```

**Comment by forkbabu** [comment]
@vanpelt not that. I meant how to hide this website interface this specifically. The env magic u suggested just stopped me from logging results. I need to disable this since it is HTML intensive and hinders the automatic saving of the colab nb.

![Screenshot from 2021-07-20 16-13-09](https://user-images.githubusercontent.com/8037297/126311124-21a0a034-f7db-4074-be21-a20db74ae5a7.png)

**Comment by vanpelt** [comment]
Ahh, I see.

```
%env WANDB_SILENT=true
```

By default, if a cell returns a run object we render the wandb ui.  If you don't want us to render the UI in that case, just set the return value of `wandb.init` to a variable.  i.e. `run = wandb.init()`

**Comment by vanpelt** [comment]
@forkbabu one more thing.  If you still want to see links to the run that's created, just don't set `WANDB_SILENT`.  It sounds like your main concern is the web interface being rendered which can be fixed by setting the return value of `wandb.init` to a variable or having something else as the final line of the cell.

I will note, that the HTML which is displayed should not at all impact the saving of the colab.  The HTML is just an `<iframe` tag with the url to the run, the actual HTML itself isn't saved within the notebook.  If you're having problems saving a colab notebook, something else could be going on.  Please provide an example notebook or the steps required to reproduce if that's the case.
