### ISSUE TITLE
[Feature] Sweeps not moved when runs are moved to another project

### ISSUE THREAD

**Issue by ashok-arjun** [wandb/client#2434]
**Is your feature request related to a problem? Please describe.**

When I move all the runs of a project associated with a sweep to another project, the sweeps still stay in the original project with the count as 0.

**Describe the solution you'd like**

I would also like the sweeps to be moved to the other project, and linked with the corresponding runs in the project.

**Additional context**

Once such runs associated with sweeps are moved, the association of the sweep with the run (and vice versa) are lost.

**Comment by tyomhak** [comment]
Hey @ashok-arjun , thank you for the feature request! This feature is in our plans,  though we can't give an ETA yet.

As a workaround for now you could [seed a new sweep](https://docs.wandb.ai/guides/sweeps/existing-project#seed-a-new-sweep-with-existing-runs) from the moved sweep runs, to have them in a single sweep in the new project.

**Comment by ashok-arjun** [comment]
@tyomhak That works, thank you for the help!

**Comment by sbiales** [comment]
This isn't super sufficient in my experience. It is difficult to know which runs were in which sweeps, and for some of my runs, it will not let me add it to a new sweep because the original sweep config.yaml had a typo in one of the parameters. I have no idea where that info is stored, since now supposedly this is just a run detached from any sweeps, but nonetheless it knows and rejects adding them. I wish I had known this before moving all my runs to another project. It should absolutely move the sweeps or at minimum warn the user that moving the runs will remove them from a sweep.
