### ISSUE TITLE
[CLI] wand.run.dir points to root (/) when running in disabled mode

### ISSUE THREAD

**Issue by mil-ad** [wandb/client#2440]
When wandb mode is set to `disabled` the `wand.run.dir` attribute points to `/`.  Is this by design or is it overlooked? 

I mostly use `wandb.run.dir` to store artifacts and saving them to root is almost never what I want (and fails due permissions anyway) Doesn't it make more sense to fallback to whatever was passed to `wand.init()`s `dir` argument or CWD?

**Environment**
- OS: Linux 5.10.52-1
- Environment: Conda
- Python Version: 3.8.10

**Comment by vanpelt** [comment]
Hey @mil-ad when running in disabled mode we create a mocked run object that returns dummy data.  Each run actually creates it's own sub directory within the `dir` specified to `wandb.init`.  Because the run is disabled, we do not automatically create this directory.  

I've created a [PR](https://github.com/wandb/client/pull/2441) that sets this to the generated directory, however that directory won't exist so if you wanted to use it you would need to create it first.

Can you share a little more about your usecase?  What's the scenario where you're completely disabling wandb and still reading writing to the wandb directory?  It could be that mode="offline" is better suited to your usecase.

**Comment by mil-ad** [comment]
I think it makes sense that wandb is not creating that dir in disabled mode, I just think that returning `/` makes this hard to catch as it's a valid path. Perhaps returning `None` makes more sense?

**Comment by vanpelt** [comment]
Hmm, I don't like the idea of `dir` not always being a string.  What if we set it to the system temp directory?

**Comment by mil-ad** [comment]
I mean, if I've specifically disabled wandb then should there even be a `wandb.run` object? let alone the `dir` attribute.  I understand that internally you might want to have a shim thing with dummy data but in terms of what gets exposed to the user it might not be the best thing.

**Comment by vanpelt** [comment]
The primary usecase for `WANDB_MODE=disabled` are users testing their ML projects in CI or CD.  In this case they want all of their code to execute properly and must depend on core wandb sdk methods to continue functioning, `wandb.log`, `if wandb.summary["acc"] > 0.5` etc.  If we didn't return a run object at all or broke any of our existing SDK methods the user code wouldn't be able to run.

**Comment by mil-ad** [comment]
Thanks for the explanation -- that makes sense. I think in case of `wandb.run.dir` it's difficult for the code to continue functioning unless you return something in `/tmp`

**Comment by vanpelt** [comment]
Cool, I've changed it to use `tempfile.gettempdir()` and will release next week.
