### ISSUE TITLE
[Feature] The order of the bars in the bar plot when using runs-grouping

### ISSUE THREAD

**Issue by jan-petrak** [wandb/client#2536]
**Is your feature request related to a problem? Please describe.**
In the online dashboard, when creating a Bar plot and applying "Group by" to runs, the bars are often not being sorted in any order.

E.g., when plotting the mean "score" of the runs, grouped by the metric "A" (with the domain { 0, 1, 2 }), the resulting bar plot looks as follows, and I can't find any option to change the order of the bars:
.............A=1
......................A=0
.....A=2

**Describe the solution you'd like**
Add the option to sort the bars in an ascending / descending order of the grouping metric domain

**Describe alternatives you've considered**
Implement a drag&drop way of re-ordering the bars

**Additional context**

**Comment by tyomhak** [comment]
Hi @jan-petrak , thank you for the feature request! I believe we have an internal ticket for this, I'll bump up the priority for it.

**Comment by cvphelps** [comment]
@jan-petrak we dug in on this and it turns out all you need to do is click the "sort" button on the top left, in the runs sidebar:
![image](https://user-images.githubusercontent.com/6355078/134707478-b7bbeb4b-c4aa-43de-84fe-d934ef9e0f8c.png)

When you apply sorting it will affect both the table and the bar chart. ✅
