### ISSUE TITLE
[CLI] wandb: ERROR Dropped streaming file chunk 

### ISSUE THREAD

**Issue by sophiaas** [wandb/client#2673]
**Describe the bug**
I'm running a sweep. I started 6 agents in parallel with that sweep id. All going fine. Then I started another 6 agents with the same sweep id in a different parallel process. Working fine at start, but after a while, I started seeing the following error on every log step:

`wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
ERROR:root:dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/[ENTITY]/[PROJECT]/c60hxx3a/file_stream
NoneType: None`

The file `wandb/debug-internal.log` is blank.

Any ideas on what might be going wrong?

**Operating System**
- OS: Ubuntu 18.04.4 LT
- Environment: Python
- Python Version: 3.9.2

**Comment by anmolmann** [comment]
Hey @sophiaas , thanks for reporting the issue. Could you please share the wandb version you're using? This was a known issue in a previous wandb version, hence, my reason for asking.
Also, can you try syncing the runs, using` wandb sync` and check if this resolves the issue? As it seems like wandb tried to upload a file that wasn’t there/available. To get to the root cause as to why this is happening - we would need more logs, I see you mentioned that debug-internal.log was empty. If possible, could you share other log files - for instance: `debug.log`, etc.

**Comment by vanpelt** [comment]
@sophiaas when you start your agent be sure to specify the fully qualified sweep name, i.e. USERNAME/PROJECT/SWEEP_ID that's my best guess as to what might be going wrong.

**Comment by Chuyun-Shen** [comment]
I met the same ERROR. When I accidentally deleted the runs on webpage, I get the same ERROR in CLI "ERROR:root:dropped chunk 404 Client Error: Not Found for url", and I can't stop it by CTRL C. My wandb version is 0.11.2.

**Comment by sophiaas** [comment]
@vanpelt I think this was my issue. I'm making sure to provide all of those details now and am no longer running into the error. Thanks!
