### ISSUE TITLE
[App] Function of agent in sweep results in an empty config if function is given input

### ISSUE THREAD

**Issue by Tobblatzius** [wandb/client#2724]
Today I tried using the sweep functionality of wandb for the first time. In my main function I load some data which I want the train function to takes as argument. However, for the sweep to work, the function in wandb.agent(sweep_id, function) can not take any arguments. If it does, the wandb.config will be an empty dictionary. Is this a bug or a design choice? If it is the later, it seems very counter-intuitive to me and should be added to the documentation.

Working example

```
import wandb
import time

def my_train_func():
    with wandb.init() as run:
        print("config:", dict(run.config))
def main():
    sweep_id = wandb.sweep({'name': 'my-awesome-sweep',
                        'metric': {'name': 'accuracy', 'goal': 'maximize'},
                        'method': 'grid',
                        'parameters': {'a': {'values': [1, 2, 3, 4]}}})
    wandb.agent(sweep_id, function=my_train_func)
        
if __name__ == "__main__":
    main()
```

Non working example
```
import wandb
import time

def my_train_func(x):
    with wandb.init() as run:
        # prints empty dict
        print("config:", dict(run.config))
def main():
    
    x = 'input which crashes program'

    sweep_id = wandb.sweep({'name': 'my-awesome-sweep',
                        'metric': {'name': 'accuracy', 'goal': 'maximize'},
                        'method': 'grid',
                        'parameters': {'a': {'values': [1, 2, 3, 4]}}})

    # this line actually runs it -- parameters are available to
    # my_train_func via wandb.config
    wandb.agent(sweep_id, function=my_train_func(x))
        
if __name__ == "__main__":
    main()
```

**Comment by armanhar** [comment]
Hey Tobias, can you specify the wandb version you are using?

**Comment by Tobblatzius** [comment]
0.12.3

**Comment by Tobblatzius** [comment]
Thanks for your reply @vanpelt , that did the trick. I have not encountered this type of issue before and think it might be helpful to add something to https://docs.wandb.ai/ref/python/agent. Regarding the constraints on the function argument.

**Comment by BingliangLI** [comment]
I suggest we should add this to the doc page of sweep quick start: https://docs.wandb.ai/guides/sweeps/quickstart because a lot of training function takes additional arguments from parser or dict, etc. And not all the parameters are need to be optimized, for example the backbone arch, the batchsize, etc. Obviously if I choose to use wandb to store all the config at the first place this won't be a problem, but if people want to modify their previous codes to use sweep this may very likely to be an issue!

I just spent hours to find this genius solution, obviously it deserves to be in the documentation👀.

> Hey @Tobblatzius when our agent executes the function we won't have access to `x`. You likely want to use [functools.partial](https://docs.python.org/3/library/functools.html#functools.partial) here, i.e.
> 
> > wandb_train_func = functools.partial(my_train_func, x)

BTW, thanks again for the answer!
