### ISSUE TITLE
[Feature] make histograms work with cuda tensors

### ISSUE THREAD

**Issue by nekomi2** [wandb/client#2946]
**Is your feature request related to a problem? Please describe.**
Because histograms use np.histogram, they don't work with cuda tensors. Instead, you have to detach the tensor, then  transfer it to the CPU, which is a hassle and slower, and isn't consistent with other data types that do work with cuda tensors.
**Describe the solution you'd like**
Make histograms natively support cuda tensors.
**Describe alternatives you've considered**
Just using the workaround as normal

**Comment by aidanjdonohue** [comment]
Hi @nekomi2, I'm a bit confused by part of your request. The data type wandb.Histogram if for datavisualization. In order to access the data and visualize it in non-cuda environments like our web app, it needs to be moved to the CPU.

Re consistency with other data types, which datatypes do we support that do work with cuda tensors?

**Comment by nekomi2** [comment]
Oops, sorry, I read the codebase I was working with again, and other data types also detach + to cpu before logging.
