### ISSUE TITLE
[Q] Use wandb.save() to save a file in a sub-folder

### ISSUE THREAD

**Issue by EmanueleFrancazi** [wandb/client#3022]
I have a file stored in a sub-folder (with respect to the python script where wandb is calledand I would like to save it at the end of the run in the same way I do with a file in the same directory of the python script (`wandb.save(filename)`). I tried with the syntax
`wandb.save(./path/to/file)` but it was not successful; how should I do it?

**Comment by ramit-wandb** [comment]
Hi @EmanueleFrancazi,

`wandb.save` is not meant to save a file locally, but it is designed to sync files that are already saved locally on W&B as well. I would recommend serializing the file as you would normally (using JSON, pickle or whichever serialization format your file supports), and then you can use `wandb.save` to sync this file on to W&B as well.

If you want to change where `wandb` is logging your data, you can do this by specifying the `dir` argument in `wandb.init`. This will log all your data associated to wandb (like run data and logs) will be stored in the directory you specified in `dir`.

**Comment by EmanueleFrancazi** [comment]
Hi ramit,
Thank you for your comment.
I think I was not clear; my purpose is indeed to sync files that are already saved locally on W&B.
The problem is that the files that I want to sync are not all in a single dir. What I'd like to do is to specify, for each single `wandb.save` call the directory's path of the file I want to sync and repeat the command for all the file I want to sync. Is it possible?

**Comment by ramit-wandb** [comment]
Hi @EmanueleFrancazi,

Thanks for the clarification. Yes, `wandb.save` allows for UNIX-style glob strings to specify multiple files together. I set up a small example to explain how you could use this:

I created a directory with the following file structure (`abc`, `def`, ... are dummy files)
```
.
├── folder1
│   ├── abc
│   └── jkl
├── folder2
│   └── def
├── folder3
│   └── ghi
├── main.py
```

Now, in order to sync all the directories up, you could do something like this:
```python3
directories = ['folder1', `folder2`, `folder3`]

run = wandb.init(project='Project')

for directory in directories:
    run.save(os.path.join(directory, '*'))   # Referring to all files in directory as directory/*

run.finish()
```

In general, any UNIX-style glob expression should work, allowing you to specify the files you want to save. You can read more about `wandb.save` [here](https://docs.wandb.ai/ref/python/save) and glob expressions [here](https://man7.org/linux/man-pages/man7/glob.7.html).

Hope this helps resolve your issue.

**Comment by EmanueleFrancazi** [comment]
Thank you! your explanation was crystal clear
