### ISSUE TITLE
[Q] Best way to log train-valid-test split when randomizing during experiments? 

### ISSUE THREAD

**Issue by Wilann** [wandb/client#3085]
Hi, 

I have a dataset which I've uploaded as an artifact, but it doesn't have a fixed train/valid/test, as I want to randomize the data in each split to get more experiment variety. Is there a way to easily log which files are in each split for a particular run? It would also be nice if it's easy to see in the UI. This would greatly help in experiment reproducibility.

**Comment by ramit-wandb** [comment]
Hi @Wilann,

If you are splitting the dataset in your code, you can store them as 3 different Artifacts as `train`, `test` and `validation`. There is no way to "split" an artifact.

Another method is to store the indices of the train, test and validation split in another file which you can refer along side your dataset.

**Comment by Wilann** [comment]
Hi @ramit-wandb, 

Thank you for the quick reply. 

Yes, I'm splitting them in my code. If I store them as 3 different Artifacts, would I have to upload them each time? They contain video files, and therefore this would take a long time for each run. 

If I were to store the indices, is there an easy way to view this file in each run in the UI (since they would be different in each run)?

**Comment by ramit-wandb** [comment]
Hey @Wilann,

If you want to view the data you have stored, I think the best way would be to upload the `train`, `test` and `validation` datasets separately. If you store them as one dataset with indices, while technically you have all the information to see which data point is in which dataset, there is no way to automatically split the data based on the indices.

Since you will be uploading the same dataset, the file sizes should be roughly the same to upload - they might be a little larger as they are being stored as 3 different objects, but this difference should be in the magnitude of kilobytes or a few megabytes.

**Comment by Wilann** [comment]
Hi @ramit-wandb,

The dataset I have is ~800 GB as I'm testing different frame features for a CV model. It would take a very long time for each run to upload my entire dataset everytime, if I understand you correctly. 

Is it possible that automatically spliting the data based on the indices can be a new feature for `wandb` in the future?

**Comment by ramit-wandb** [comment]
Hi @Wilann,

I understand your problem. Yes, clearly it does not make much sense to upload the same 800GB dataset repeatedly. I'm going to create a request for a feature to easily log `train`/`test`/`validation` splits in our UI, and I'll follow up here once I have some news on this feature.

Thanks,
Ramit

**Comment by Wilann** [comment]
Hi @ramit-wandb, 

Thank you for creating a feature request with your team. For now, I will log a text file as an Artifact with indices to data. As you say, in this case, I can still see how my data is split, albeit a bit inconvenient. 

Will close the issue for now. Looking forward to potentially this feature being added in the future.
