### ISSUE TITLE
[Q] Adding a collaborator to existing project

### ISSUE THREAD

**Issue by ahaliassos** [wandb/client#3158]
Hi, fantastic work, have been using it for a while! 

I know how to create a new project with a specified team, but I would like to add someone to an existing project so that he can view all the experiments that have already been run. Is this possible?

**Comment by ramit-wandb** [comment]
Hey @ahaliassos!

Yes, you can invite members to your team from the Team settings page. You can find it at https://wandb.ai/teams/<YOUR_TEAM_NAME>

Thanks,
Ramit

**Comment by ahaliassos** [comment]
Thanks for your quick response! 

I realise that it's possible to add people to a team, but what if the project in question does not correspond to a team but only to a single user? Is it still possible to somehow add people to that project?

**Comment by ramit-wandb** [comment]
Hi @ahaliassos,

You can make your project public so that anyone can view it, or use our [View Only Reports](https://docs.wandb.ai/guides/reports#view-only-report-links) feature to create reports that only selected people who have the report link can view. If you want to collaborate with anyone on a project, however, they must be in a team with you.

Thanks,
Ramit

**Comment by ahaliassos** [comment]
OK, thanks for clearing it up!
