### ISSUE TITLE
[Q] Sweeps with torchun

### ISSUE THREAD

**Issue by rvandeghen** [wandb/client#3225]
Hi,

What should I do to use sweep with `torchrun`
 I tried `program: torchrun --nproc_per_node=4 src/train.py` but it does not work.

**Comment by aidanjdonohue** [comment]
Hi @rvandeghen , that's a very good question. Are you using the `command` sweep argument? You can read more about how to format this [here](https://docs.wandb.ai/guides/sweeps/configuration#command). I would try replacing `- ${interpreter}` with torchrun and pass the additional params like the examples show.

**Comment by rvandeghen** [comment]
@aidanjdonohue Indeed after some tests, the correct usage is:
```
command:
- torchrun 
- --nproc_per_node=4
- train.py
```
as you mentioned. However, it is still not fully clear how to use it when you track the log on only one node.

**Comment by aidanjdonohue** [comment]
@rvandeghen, I don't know if I fully understand your question. Could you please elaborate?

**Comment by rvandeghen** [comment]
@aidanjdonohue I followed [https://docs.wandb.ai/guides/track/advanced/distributed-training](url) to log only on one node but I still need to pass the sweep arguments to the other ones. I use `torch.distributed.broadcast_object_list()` and `torch.distributed.barrier()` but the script seems to freeze at some point. I still need to debug it.

**Comment by aidanjdonohue** [comment]
@rvandeghen, here's a slightly more thorough [example](https://github.com/wandb/examples/tree/master/examples/pytorch/pytorch-ddp). 

Have you tried setting `WANDB_START_METHOD = "thread"` and ensuring that you explicitly finish all runs with `run.finish()`?

**Comment by sydholl** [comment]
Hi @rvandeghen - following up on this, have you been able to try setting `WANDB_START_METHOD = "thread"`?

**Comment by marsggbo** [comment]
> @aidanjdonohue I followed [https://docs.wandb.ai/guides/track/advanced/distributed-training](url) to log only on one node but I still need to pass the sweep arguments to the other ones. I use `torch.distributed.broadcast_object_list()` and `torch.distributed.barrier()` but the script seems to freeze at some point. I still need to debug it.

Hi @rvandeghen , I've also encountered this problem. Have you solved this problem?

**Comment by hlzhang109** [comment]
same. how to specify master_port in torchrun? the sweep is quite incompatible with distributed torch, how to configure wandb sweeps with torchrun master_port?

the yaml looks like
command:
  - "torchrun"
  - "--nproc_per_node=2"
  - ${program}
  
If we do wandb sweep xx.yaml and then wandb agent/yyyy, it would get `RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to ?UNKNOWN? (errno: 98 - Address already in use)`, even if I set os.environ['MASTER_PORT'] internally, because the bug occurs before the line of code.
