### ISSUE TITLE
[CLI] No config file in offline mode

### ISSUE THREAD

**Issue by proceduralia** [wandb/client#3249]
**Description**
No config file seems to be created when offline mode is selected. This prevents grouping and identification of runs when they are then manually synced to the server.

**Wandb features**
When the init function is called as `wand.init(mode='offline',...)`, the metrics seem to be correctly logged, but, under the run directory, the `files/` subdirectory will contain no `config.yaml` file, preventing correct logging of configuration.

**Environment**
- OS: Ubuntu 20.04.3
- Python Version: [eg. 3.8.10]

**Comment by ramit-wandb** [comment]
Hi @proceduralia,

I just tested this on Ubuntu 20.04.3, and it generated the `config.yaml` file for me. Could you share a link to the project where you experience this?

A small script reproducing this behavior would also be very helpful in figuring out why you are experiencing this issue.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hey @proceduralia,

You can use [`wandb sync`](https://docs.wandb.ai/ref/cli/wandb-sync) to sync your files. Usually, you can start using `wandb sync` a few minutes into your experiment (so that the file to be sent to W&B is populated with some information) and it should work as expected.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @proceduralia, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by twni2016** [comment]
Hi @ramit-wandb this issue is not resolved in my case. This is a simple script to reproduce the issue:
```python
    wandb.init(
        project=wandb_project_name,
        entity=wandb_entity,
        dir=log_path,
        mode="offline",
    )
    wandb.config.update(
          config_dict,
    )
# wandb.log 
```
The problem only happens in the `offline` mode. I think I use the same remote cluster as @proceduralia, which does not have internet access. 

I found `config.yaml` *almost always* does not exist in the `offline-run-*/files/` folder, even when the run is finished. With some exception, the `config.yaml` only have `_wandb` key, but not have the information of `config_dict`.

Could you help me with this issue? Actually, this is one of the biggest reasons for me to use wandb.

**Comment by dave4422** [comment]
I've got the same issue. Did you resolve it?
