### ISSUE TITLE
How to use grouping in wandb.Image

### ISSUE THREAD

**Issue by amir-abdi** [wandb/client#330]
* Weights and Biases version: 0.7.3
* Python version: 3.5.2
* Operating System: Ubuntu 16.04

### Description

In logging images, I try to group them into certain groupings. However, it seems that the "grouping" attribute of the wandb.Image class is being ignored or I don't know the proper way to do it. I could not find any documentation which explains this.

I tried setting grouping to 
- an integer (how many to group),
- a list of integers with same size as number of images, each setting the group for one image

The wandb interface keeps on showing images in 8 columns with no grouping.

**Comment by vanpelt** [comment]
Hey @amir-abdi sorry for the delayed response.  Currently the frontend is not using the "group" parameter (it's intended to be an integer).  We have a feature on the roadmap to implement it.  I'll keep this open and update this once it is.

**Comment by amir-abdi** [comment]
Hi @vanpelt 
Thank you for your response.
So, is there any way I can visualize the images I am logging using `wandb.log({'images':wandb.Image(...)})` into grids of more than 8 columns?

Example:
![image](https://user-images.githubusercontent.com/4620480/57893314-459c2800-77f7-11e9-9eb5-2fc9b3fdea7c.png)

**Comment by vanpelt** [comment]
It's likely easiest to make the grid on your own using matplotlib or something like `torchvision.utils.make_grid` then logging that as an individual image.

**Comment by MasterScrat** [comment]
I am not sure if my question relates to the same problem, but when I use a group in my config (eg `group: run001`), I don't see how I can use this group as a filter from the UI.

I do not see a "Filter" criterion on the Filter menu on the left in the project page.

However, I see that from my profile page, some of the runs specify that they are grouped runs (eg "(6 runs)") and when I click them I am taken to a page with the URL of the form `groups/run001`, which is what I was looking for.

How can I reach this page from the project page, instead of from my profile page?

**Comment by vanpelt** [comment]
Hey @MasterScrat on a project page you can configure grouping in the table:

![Screen Shot 2019-11-11 at 5 12 18 PM](https://user-images.githubusercontent.com/17/68691750-19086500-0529-11ea-9ab1-444d2efca7d7.png)

This will make all rows in the table grouped, and clicking on a row will take you to the group page you mentioned.  Does that make sense?

**Comment by MasterScrat** [comment]
Thanks @vanpelt this is useful!
However, I used the `group` argument of `wandb.init()` when initializing my training session, and I don't see this group showing up in this list?
Is this maybe because, as you said earlier in this thread, this parameter in supposed to be an integer? I'm using the format "run001".

I realise I could use a custom `config` key-value pair but I want to make sure I'm doing things right!

**Comment by vanpelt** [comment]
This ticket is actually about the group parameter to wandb.Image which is different than run level grouping.  If you specified group in in your call to init, you should see "group" as an option in the group by dropdown.  Can you link me to the project where you're not seeing it?

**Comment by ariG23498** [comment]
Hey @MasterScrat 
Did you happen to find a solution to the problem? The thread has gone stale over a year. It would be great if you could give us your feedback on the issue.
CC: @cvphelps @vanpelt
