### ISSUE TITLE
[Q]Is there some way to automatically save the best run with sweep?

### ISSUE THREAD

**Issue by drxmy** [wandb/client#3354]
I have seen this issue #3244 . But with these best params, I may have to train it again which is sad. By the way, is there  some way to automatically save the best hyper-parameters?

And I am using wandb with hugging face.  
Thank you for the wonderful wandb.

**Comment by ramit-wandb** [comment]
Hi @drxmy,

We do save the best hyperparameters with `sweep.best_run().config`. But even with those, you would have to re-train the model. Since your purpose here is to not re-train the model, you may be talking about model parameters.

We can not know a priori if a model is going to produce good results or not, so if you want the best parameters - the way to do this would be to store all your model files associated to a sweep as an [Artifact](https://docs.wandb.ai/ref/python/artifact). One potential way to only store better models in a sweep would be to have a condition in your code such as:

```python
if current_model_loss < api.Sweep('...').best_run.config['loss']:
    # Store model artifact
    artifact = wandb.Artifact(...)
    ...
    run.log_artifact(artifact)
```

Please let me know if I can assist further.

Thanks,
Ramit

**Comment by drxmy** [comment]
> Hi @drxmy,
> 
> We do save the best hyperparameters with `sweep.best_run().config`. But even with those, you would have to re-train the model. Since your purpose here is to not re-train the model, you may be talking about model parameters.
> 
> We can not know a priori if a model is going to produce good results or not, so if you want the best parameters - the way to do this would be to store all your model files associated to a sweep as an [Artifact](https://docs.wandb.ai/ref/python/artifact). One potential way to only store better models in a sweep would be to have a condition in your code such as:
> 
> ```python
> if current_model_loss < api.Sweep('...').best_run.config['loss']:
>     # Store model artifact
>     artifact = wandb.Artifact(...)
>     ...
>     run.log_artifact(artifact)
> ```
> 
> Please let me know if I can assist further.
> 
> Thanks, Ramit

Thank you for your reply! I will give it a try.
