### ISSUE TITLE
[Q] Maybe avoid use '-' in the wandb filename

### ISSUE THREAD

**Issue by SingletC** [wandb/client#3420]
Hi, The '-' symbol in the filename cause windows cannot handle it correctly (remove, rename). Would that be better if wandb use underscores instead?

**Comment by ramit-wandb** [comment]
Hi @SingletC,

Thanks for writing in! Could you share some more information about the issue you are facing? It will really help us understand the problem here. Specifically:

- Where exactly do you mean we should change  '-' to '_'?
- What issues exactly are '-' characters creating?

Any other information you might think is relevant would be useful.

Thanks,
Ramit

**Comment by SingletC** [comment]
> Where exactly do you mean we should change '-' to '_'?
The file generate by wandb after wandb.init()
e.g.  a folder inside wandb named ''run-20220110_204704-37pqmla3"
>What issues exactly are '-' characters creating?
Windows does not allow - symbol in the name of file/folder, default file explorer will not able to move/delete such file. I have to use cmd or other software to do so.

**Comment by SingletC** [comment]
sorry, it is an issue with my IDE. please ignore this issue.
