### ISSUE TITLE
[CLI]: _disable_stats doesn't work

### ISSUE THREAD

**Issue by CosmicHazel** [wandb/client#3505]
### Describe the bug

`_disable_stats` doesn't work. `wandb.init(settings=wandb.Settings(_disable_stats=True))` It still sends stats to WANDB, which in turn leads to BSOD due to incompatibility with the old PYNVML dependency in the vendor folder in very specific scenarios.

```
wandb.init(settings=wandb.Settings(_disable_stats=True))
```

None

### Environment

WandB version:
0.12.14

OS:
Windows 10

Python version:
 3.9.10

**Comment by dmitryduev** [comment]
Hey @CosmicHazel, many thanks for reporting this! 
This should be fixed in https://github.com/wandb/client/pull/3510, but for now, instead of passing a `wandb.Settings` object to `init()`, please try passing a simple dict, as in `wandb.init(settings=dict(_disable_stats=True))`. 
Also, could you please elaborate on the dependency incompatibilities that you are observing?
