### ISSUE TITLE
[Feature]: Don't raise the traceback when a KeyBoardInterrupt is raised.

### ISSUE THREAD

**Issue by tchaton** [wandb/client#3524]
### Description

As a user, I always get annoyed when the traceback is raised when I click ctlr + C. I wished the Wandb Client captured it and just put a successful message there.

### Suggested Solution

Capture traceback

### Alternatives

.

### Additional Context

.

**Comment by ramit-wandb** [comment]
Hi @tchaton!

Thanks for the suggestion! I can escalate this to our engineering team for review. I'm curious about your use case here and how this feature would be useful to you. 

One concern I foresee with this issue is if we start catching and obfuscating Tracebacks, this might hide away some essential information that might be required to debug code (for e.g. if the code is hanging, the `KeyboardInterrupt` traceback is useful to get a sense for where the code is hanging). I would love to hear your thoughts on this and how we could might be able to get the best of both - catching the `KeyboardInterrupt` when it is not needed and printing it when it is useful.

Thanks!
Ramit

**Comment by ramit-wandb** [comment]
​Hi @tchaton,

We wanted to follow up with you regarding your support request as we have not heard back from you. I would love to hear your thoughts on this so that we can come up with a reliable solution for your use case.

Best,
Ramit
​

**Comment by ramit-wandb** [comment]
​Hi @tchaton, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
