### ISSUE TITLE
Calling writer.add_scalars(...) with a PyTorch TensorBoard SummaryWriter raises unexpected warnings.

### ISSUE THREAD

**Issue by elliotwaite** [wandb/client#357]
* Weights and Biases version: wandb 0.8.1
* PyTorch version: pytorch 1.1.0
* TensorBoard version: tb-nightly 1.14.0a20190530
* Python version: 3.7.3
* Operating System: macOS 10.14.5

### Description

Calling writer.add_scalars(...) with a PyTorch TensorBoard SummaryWriter raises unexpected warnings.

This may be an issue with PyTorch rather than W&B, but wasn't sure.

### What I Did

Ran this python code:
```
import torch.utils.tensorboard
import wandb

writer = torch.utils.tensorboard.SummaryWriter()
wandb.init()
wandb.tensorboard.patch(tensorboardX=False, pytorch=True)

scalars = {
    'scalar_1': 1.0,
    'scalar_2': 2.0,
    'scalar_3': 3.0
}
writer.add_scalars('test', scalars, global_step=1)
```

Unexpected warnings:
```
wandb: WARNING Adding to old History rows isn't currently supported.  Step 0 < 1 dropping: {'scalar_2/global_step': 0, '_timestamp': 1559366850.7236722}
wandb: WARNING Adding to old History rows isn't currently supported.  Step 0 < 1 dropping: {'scalar_3/global_step': 0, '_timestamp': 1559366850.724994}
```
The global_step should be 1 for all of the scalars, but it's only being set to 1 for scalar_1. Then when it tries to add scalar_2 and scalar_3, which are given a global_step of 0 for some reason, it raises these warnings saying that old history data can't be added.

**Comment by vanpelt** [comment]
This is an issue with wandb's tensorboard logging integration.  It will still log scalars, just one step behind.  If you can share a small code snippet that reproduces this I can see if there's a way to handle this case.

**Comment by elliotwaite** [comment]
The code snippet in the initial post should reproduce the issue. Let me know if you don’t see the same warnings when you run it.

**Comment by ariG23498** [comment]
Hey @elliotwaite 
I tried recreating your code as follows:
```python
from torch.utils.tensorboard import SummaryWriter
import wandb
wandb.tensorboard.patch(tensorboardX=False, pytorch=True)
wandb.init()
writer = SummaryWriter()
scalars = {
    'scalar_1': 1.0,
    'scalar_2': 2.0,
    'scalar_3': 3.0
}
writer.add_scalars('test', scalars, global_step=1)
writer.close()
wandb.finish()
```

My observations:
1. The `writer.close()` is an important piece of code that is left out in your code snippet. When I used your code snippet the tensorboard integration in colab and weights and biases would not even recognise any event files that are logged.
2. The warning that you have pointed out to are no longer prevalent. I did not face any of the warning that have been stated above.
3. There is a warning that I face with my implementation which is as follows:
```
wandb: WARNING When using several event log directories, please call wandb.tensorboard.patch(root_logdir="...") before wandb.init
```
I have tried figuring out the `root_dir` parameter, due to the unavailability of a docstring or documentation, I was not able to remove the warning.
4. If we ignore the warning the tensorboard integration in wandb does not really work like the one in colab.
|The file structure of the event files that are logged by the `SummaryWriter` are|But in the wandb folder the event files are not structured the same way|
|---|---|
|![image](https://user-images.githubusercontent.com/36856589/100377748-d9c78c00-3037-11eb-9f97-959f83fca1cd.png)|![image](https://user-images.githubusercontent.com/36856589/100377787-f663c400-3037-11eb-9040-e58ba85a4305.png)|

Here we do not see the folders namely `test_scalar_1`, `test_scalar_2`, `test_scalar_3`.

This leads us to the bug in the tensorboard integration

| **Colab tensorboard** | **Tensorboard in wandb**|
|---|---|
|![image](https://user-images.githubusercontent.com/36856589/100377922-42166d80-3038-11eb-998e-1e2eb599182f.png)|![image](https://user-images.githubusercontent.com/36856589/100378164-9588bb80-3038-11eb-885a-2aaaf4219cd5.png)|

Here we do not notice the anything in the `runs` section of `wandb tensorboard`.

I am suspecting a probable issue with https://github.com/wandb/client/blob/30f77c8a320fe42a519f76eb012e61101afad9ba/wandb/integration/tensorboard/monkeypatch.py#L90

CC: @cvphelps @vanpelt

**Comment by elliotwaite** [comment]
Got it. Thanks for following up on this. I have stopped using the Tensorboard integration and now just use the wandb backend directly, so this issue is no longer affecting me and I don't have Tensorboard installed anymore to test this code. Feel free to close this issue if it is resolved or not affecting others.
