### ISSUE TITLE
[Q] How to continue run the unfinished specific sweep?

### ISSUE THREAD

**Issue by cuiyc2000** [wandb/client#3725]
I have several successful runs in a sweep. However, somehow I encountered a failed run for some unknown error. It's hanging for waiting the job, so I killed the process. How could I continue the run only using the unfinished config without restart the whole sweep?  I'll be very grateful for your help.

**Comment by ramit-wandb** [comment]
Hi @cuiyc2000,

You should simply be able to call `wandb agent` the way you did before to continue your sweep.

**Comment by cuiyc2000** [comment]
> Hi @cuiyc2000,
> 
> 
> 
> You should simply be able to call `wandb agent` the way you did before to continue your sweep.

If I delete a run, is wandb gonna rerun it with its config？

**Comment by ramit-wandb** [comment]
Depends on the search strategy - if you were using a `grid` search, yes the agent will create a run for the exact same run configuration (since a grid search is an exhaustive search of your config). `bayes` and `random` search sample from a distribution, so there is a probability to run the same config, but for most configs to control a neural network, the chance of you reaching the same config is low - specially if you have a continuous distribution like `normal` or `uniform` defined in your config.
