### ISSUE TITLE
CLI hangs indefinitely when it can't talk to host

### ISSUE THREAD

**Issue by vanpelt** [wandb/client#38]
* Weights and Biases version: feature/streaming_and_wandb_run
* Python version: 3.6
* Operating System: Mac

### Description

If the cli can't talk to the server, it will hang retrying indefinitely

### What I Did

Just set the base uri to something invalid or to a not running local instance and run a command that talks to the server.

**Comment by shawnlewis** [comment]
I was trying this earlier and it doesn't seem to hang forever:

I set base_url to "http://laksdjflkajsdfklajsdfkljasdflkjasdflkjasdf.com"

(wandb_cli-3.6) Shawns-MacBook-Pro:client shawn$ wandb projects
Error: An Exception was raised, see .wandb/debug.log for full traceback.
wandb.api.CommError: HTTPConnectionPool(host='laksdjflkajsdfklajsdfkljasdflkjasdflkjasdf.com', port=80): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10f70dc88>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

Can you still reproduce?

**Comment by adrianbg** [comment]
It retries forever for me. Maybe this has changed in some cases since Run creation got moved to the wandb process where it is subject to the 1-day retry limit?

**Comment by vanpelt** [comment]
I think the behavior should be as follows:

1. Always allow the user process to run even if wandb is down.
2. Keep retrying as it does now when the user process is running.
3. In the final sync step, if the process is attached / allows user input only retry for 1 minute before saying we couldn't connect and giving control back to the user.
4. In the final sync step, if the process is detached attempt to retry for an hour.

**Comment by adrianbg** [comment]
I agree at least about 1 and 2. Need to look at the code to see how hard it is - the tough part might be not having a real run with a storage ID, whereas most of the code assumes it does have one.

**Comment by shawnlewis** [comment]
I think i might disagree about 3 and 4. In the Jenkins automation case,
 it’s better if we hang for a long time, that way data isn’t lost (When a
Jenkins job ends its possible/likely that they throw away the local fs).

**Comment by shawnlewis** [comment]
Oh I see what you mean attached v detached. Ok yeah makes sense. But
attached may mean attached to tmux or even nohup so I think we should raise
both limits. Maybe 1 hour / 24 hours, and make sure we print a good warning
about what’s going on (or even both 24 hours, user can always ctrl-c).

**Comment by adrianbg** [comment]
The storage ID doesn't seem to be an issue for the user process.

The main obstacles I can see to running the user process even when wandb is down is that we lose the ability to crash if there's an error (permissions etc) creating the run. maybe we should try creating the run once, and if wandb is down, let the user process run while we retry creating the run.

Resuming might be another issue.
