### ISSUE TITLE
Onboarding: Add "entity=teamname" to the project onboarding page

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#380]
I followed instructions under
https://app.wandb.ai/cybertronai/moonscrub

which is a team project I created

But the resulting project got created under
https://app.wandb.ai/yaroslavvb/moonscrub

Do you I need to do something special to get the logging to go under a team project?

**Comment by vanpelt** [comment]
You can either set `entity="cybertronai"` in your call to `wandb.init` or goto https://app.wandb.ai/settings and change the setting "Default location to create new projects"

**Comment by yaroslavvb** [comment]
thanks, that works

**Comment by yaroslavvb** [comment]
I think the new project instructions need to be updated, it gives the wrong init command
https://app.wandb.ai/testtest/test

![Screenshot 2019-06-19 18 06 42](https://user-images.githubusercontent.com/23068/59811049-02811900-92bd-11e9-93a9-d2b714a3977a.png)

**Comment by vanpelt** [comment]
Gotcha, will-do!

**Comment by Avuerro** [comment]
Hey, I stumbled on this issue because I was experiencing the same problems as the creator of this issue. The new project instructions  do not mention anything about the entity setting. The project was created under the wrong team even though I had set the "default location to create teams". Adding the entity parameter to the init call fixed it for me.

**Comment by vanpelt** [comment]
Hey @Avuerro what's your wandb username, we can check the settings on the server.  It should send data to your default entity set on your settings page here:  https://app.wandb.ai/settings  Assuming you're using an API key on that page.

**Comment by Avuerro** [comment]
hey @vanpelt , my wandb username is "whydoihavetoregister" which is a indeed a bit peculiar username. However at the time of registering, because I was invited by a group member, I had no idea what wandb was. 

Anyway, I have two teams A and B and initially A was the default location to create new projects. Whenever I would initialize a project it would appear under project A. I deleted the newly created project (under team A) and changed the setting default location to create new projects to B. Finally, I initialized the project but unfortunately it would still appear at team A. I googled and stumbled upon this issue. I have set the entity to B and after initializing the project it appeared under B.

**Comment by ariG23498** [comment]
Hey @Avuerro 
I have tried out doing the same and it works fine for me.
Could you please check and see whether the same problem still persists?
The thread has gone stale and we would like to close this if the issue has been resolved! :smile:

**Comment by ariG23498** [comment]
Hey folks
We have added the feature request on the on boarding page :smile: 
![image](https://user-images.githubusercontent.com/36856589/104745245-e0d76480-5773-11eb-8a9a-6ce7d1dea024.png)

Closing this ticket here. Please feel free to tag me and ask to reopen the ticket if need be,
