### ISSUE TITLE
Add run name to tensorboardx patch

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#427]
wandb, version 0.8.5
Python 3.7.3
Linux

Please change the "run name" to the name provided name by SummaryWriter through tensorboardX.

**Comment by vanpelt** [comment]
Hey dream flasher, do you mean the name of the tfevent file?   Would you want the machine and timestamp included as well?

**Comment by dreamflasher** [comment]
I mean this `writer = SummaryWriter(experiment_unique_name)`
I'd appreciate if this name shows up as the run name. 
Currently the run names are "clear-sunset-60" and thus meaningless.

**Comment by dreamflasher** [comment]
Thanks for pointing out that I can call `wandb.init(name=unique_name, sync_tensorboard=True)` to specifiy the name. That works for me, but I think it would still be nice to have that synced right away.

**Comment by ariG23498** [comment]
Hey @dreamflasher 
I think due to the fact that [https://pytorch.org/docs/stable/_modules/torch/utils/tensorboard/writer.html#SummaryWriter](SummaryWriter) takes the `log_dir` as the directory in which the tf event files would log, wandb would not have any way to figuring out the name of the directory. It would be beneficial to use either the `init` as you mentioned, or using `filename` as a variable and using it in the `init` for naming the run as you want.

CC: @cvphelps
