### ISSUE TITLE
wandb.log delayed

### ISSUE THREAD

**Issue by psinger** [wandb/client#554]
I am running `wandb.log({"loss":loss}, step=epoch)` at the end of every epoch. However, the logs are delayed 1-2 epochs in each iteration. This means that I am seeing the logs for the first epoch only on the platform when the second or third epoch is finished. Unfortunately, after stopping the code the last epochs are then not in the logs and are missing.

Any ideas?

**Comment by raubitsj** [comment]
That is concerning, can you link a URL of a run where this is happening?

**Comment by psinger** [comment]
Unfortunately, I am currently using a private repo I cannot share.

**Comment by raubitsj** [comment]
Thank you for sample, I have reproduced this in a notebook environment and am working on a solution.

**Comment by vadapalliravikumar** [comment]
I am also seeing the same issue

**Comment by psinger** [comment]
This is indeed a major bug to me that needs to be fixed asap. Any updates on it?

**Comment by vanpelt** [comment]
@psinger @raubitsj is looking into this.  Apologies for the delay, we'll get a patch out ASAP.

**Comment by vanpelt** [comment]
Hey @psinger @vadapalliravikumar the long term fix is a bit more involved but we better understand the underlying issue.  The problem is we use the `step` argument to decide when to push metrics to the server (only when it increases).  Unfortunately in jupyter we don't handle the final step properly and this also creates a delay in metrics being pushed until the step increases.  The quick fix is to not specify step and instead use the `commit` argument if you need to rollup metrics in a single step.  i.e.

```python
wandb.log({"acc": 0.5}, commit=False)
# Some other code
wandb.log({"val_acc": 0.6, "custom_step": 32})
```

Every time `wandb.log` is called without a step argument or with `commit=False` we increment an internal step counter and push the metrics to the server.  If you want to keep track of a different step counter you can pass it into log just like any other metric.  We then allow you to change the x-axis in the UI to any metrics you've logged that are monotonically increasing.

I know this is unfortunate.  We're working on a big overhaul of our backend that should address these issues and make for a cleaner api.  And again, apologies for not getting back to you sooner on this one.

**Comment by numpee** [comment]
Hi, any updates on this? I seem to be running into the same issue (using wandb version 0.8.32)

**Comment by vanpelt** [comment]
We made some improvements to the jupyter integration in 0.8.35.  @numpee can you provide us with an example notebook exhibiting the behavour you're seeing?  I just created a [colab](https://colab.research.google.com/drive/13yktq4kmYlbOQ7txvWYy04VO5hLV1DBY?usp=sharing) that asserts all metrics are being logged in the simple case.

**Comment by numpee** [comment]
@vanpelt Here's a simple code that I tried on my jupyter:
```
import wandb
wandb.init(project='rand_project')

# New cell:
i = 0
val = i * 2
wandb.log({'test': val}, step=i)
```
When I run the last cell repeatedly while increasing the value of i (by 1), the log only appears after I've run a few extra increments - no matter how long I wait. I've attached a screenshot of my jupyter code & output below:
![image](https://user-images.githubusercontent.com/29429992/80909675-131b7000-8d65-11ea-9b8a-8b5b353ce5ac.png)

I've noticed a couple of weird things:
- when printing the run.history(), only the steps that didn't display the "Upgrade wandb"  warning were logged.
- The last log has step 3 with a logged value of 8, which seems to be a merged from i=3 and i=4? This is weird and it's not something that I've encountered when actually using wandb for my experiments.


So I understand that this thread is somewhat focused on jupyter, but I usually just run wandb through a python file. In previous versions (around October/November last year) I noticed that every single log was delayed by 1 step, and the final step never logged. Now, after upgrading to 0.8.32, it seems that although **all steps are always logged, they always seem to be delayed**, no matter how much time passes between the logging steps (my loggging steps are usually 5~15 minutes apart). While I feel that this is not an app-breaking bug, it is a slight nuisance (in an otherwise amazing app). Whenever I need instant feedback on my model's performance, I end up relying more on the terminal output than I do on the wandb client. 

Again, not the biggest issue in the world, but definitely needs to be mentioned. I've just upgraded to 0.8.35, so I'll check again and see if anything has changed :)

**Comment by vanpelt** [comment]
Please try this again with 0.8.35 we made some big changes to the Jupyter integration that *should fix your issues.

**Comment by ariG23498** [comment]
Hey @numpee @psinger 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by glenn-jocher** [comment]
> I quickly made an example demonstrating this:
> 
> ```
> for i in range(5):
>     wandb.log({"loss": i}, step=i)
> ```
> 
> https://app.wandb.ai/ph_singer/test/runs/folififw?workspace=user-ph_singer

Unfortunately in this example if every step takes a long time (as is typical in ML workflows, i.e. 30 minutes), then the current metrics are seriously delayed from displaying in the dashboard.

**Comment by raubitsj** [comment]
@glenn-jocher:
When you specify step to the log method we do not immediately commit the data so that you can add more info to that step later.   If you want it to be committed to the dashboard immediately do:
```
for i in range(5):
    wandb.log({"loss": i}, step=i, commit=True)
```

**Comment by glenn-jocher** [comment]
@raubitsj ah, thanks for the tip. Is there a way to independently request a commit of the currently held data without adding additional data, i.e. perhaps `wandb.commit()` or similar?

The reason I ask is our `wandb.log(..., step=epoch)` call is in a for loop that's shared with other loggers:
```python
            for x, tag in zip(values, tags):
                if tb_writer:
                    tb_writer.add_scalar(tag, x, epoch)  # tensorboard
                if wandb:
                    wandb.log({tag: x, step=epoch})  # W&B
```

**Comment by vanpelt** [comment]
@glenn-jocher we can only `commit` data once per step.  When you're specifying `step` we only commit the data when the step increases.  If you want precise control of when we commit the data, I would not specify step and instead store your x-axis in a custom metric.  For example:

```
for x, tag in zip(values, tags):
   if tb_writer:
       tb_writer.add_scalar(tag, x, epoch)  # tensorboard
   if wandb:
       wandb.log({tag: x, epoch: epoch})
```

Will commit tag and epoch immediately.  If you want to compare multiple metrics on the same chart: i.e. loss, and val_loss, you should commit them at the same time.  If you specify `commit=False` we'll "rollup" the calls to wandb.log and only commit the results in `commit=True`, i.e.

```
for i in range(12):
   wandb.log({"loss": x, "val_loss": y, "epoch": i / 3}, commit=i % 3 == 0)
```

**Comment by glenn-jocher** [comment]
@vanpelt thanks for the ideas! That last code snippet of yours looks interesting. I experimented with including `epochs` in the dictionary, but realized it required additional steps on the dashboard to select it as the default x axis, and also added an unwanted `epochs` (on the y axis) chart to the default dashboard as well (didn't want to confuse new users).

I was thinking of settling on this hack to force a commit on last log:
```python
            for i, (x, tag) in enumerate(zip(values, tags)):
                if tb_writer:
                    tb_writer.add_scalar(tag, x, epoch)  # tensorboard
                if wandb:
                    wandb.log({tag: x, step=epoch}, commit=i == len(tags) - 1)  # W&B
```

**Comment by thenewera-ru** [comment]
> @glenn-jocher we can only `commit` data once per step. When you're specifying `step` we only commit the data when the step increases. If you want precise control of when we commit the data, I would not specify step and instead store your x-axis in a custom metric. For example:
> 
> ```
> for x, tag in zip(values, tags):
>    if tb_writer:
>        tb_writer.add_scalar(tag, x, epoch)  # tensorboard
>    if wandb:
>        wandb.log({tag: x, epoch: epoch})
> ```
> 
> Will commit tag and epoch immediately. If you want to compare multiple metrics on the same chart: i.e. loss, and val_loss, you should commit them at the same time. If you specify `commit=False` we'll "rollup" the calls to wandb.log and only commit the results in `commit=True`, i.e.
> 
> ```
> for i in range(12):
>    wandb.log({"loss": x, "val_loss": y, "epoch": i / 3}, commit=i % 3 == 0)
> ```

I think it worth adding that by saying «rolling up» you essentially mean «ignoring all the values with `commit=False`».

The only useful use-case of passing `commit=False` is when you have pipeline of sequential calculation (e.g. each batch) and you can only call all loggers in one function, one call at a time (for any reason).
For every other situation you can simply 
```
if time_to_log:
   wandb.log({
      'loss': ...,
      ...
   })
```

**Comment by RylanSchaeffer** [comment]
@vanpelt I just ran into this issue and I'm a bit confused. What's the right way to add data (scalars, plots, whatever) at the same step with `wandb.log()` calls sprinkled throughout code? It looks like the answer is that I have to wait for the step to increase?

**Comment by mranzinger** [comment]
I'm actually running into this exact problem (still) with version `0.15.8`.

Here's my log line: `wandb.log(rowd, step=num_samples, commit=True)` and even with the `commit=True`, the log of the current values is delayed until the next time I call `wandb.log` at the next epoch boundary. As others have mentioned, this causes a real-time delay of about 30 minutes for me, which is very undesirable.

Are the previous responses correct? I actually have to omit the `step` argument to the function for this to work properly? If so, I really don't understand what `commit=True` means.

**Comment by Boltzmachine** [comment]
It is 2025 now. Still the same issue. Is there a workaround?
