### ISSUE TITLE
Error when debugging in Visual Studio Code

### ISSUE THREAD

**Issue by BigBadBurrow** [wandb/client#741]
I've been using W&B v0.6.34 successfully for a few months, and I could debug within Visual Studio Code, but I'd get a warning that W&B wouldn't log anything because it hadn't been executed via this:

`wandb run python <script>`

Warning given was:

> wandb: ERROR: Headless mode isn't supported on Windows. If you want to use W&B, please use "wandb run ..."; running normally.

That was fine, as I didn't want to log out when I was debugging anyway, but now after updating to v0.8 I get an error when I try to debug:

```
wandb: Tracking run with wandb version 0.8.19
wandb: ERROR W&B process (PID 3988) did not respond
wandb: ERROR W&B process failed to launch, see: C:\Users\USER\AppData\Local\Temp\wandb-debug.log

  File "c:\Development\Coding\Test.py", line 778, in main
    wandb.init(project="tester")
  File "C:\Anaconda3\envs\pytorch-gpu\lib\site-packages\wandb\__init__.py", line 1067, in init
    _init_headless(run)
  File "C:\Anaconda3\envs\pytorch-gpu\lib\site-packages\wandb\__init__.py", line 296, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb\debug.log
```

Am I right in thinking there was a recent change so that it doesn't need to be executed like this

`wandb run python <script>`

and would work by simply doing:

`python <script>`

?

If so, I suspect that's why it's failing as it can't successfully attach to the VSC debug process.  How do I get around this please?

Thank you.

**Comment by raubitsj** [comment]
We did make windows work more like Linux/macos so you no longer need to do wandb run and can start your program with python directly.

The error you are seeing might be caused by a few things.  Can you try again with 0.8.21 and if it fails send us your debug.log file.  One possibly is there are too many untracked files in your git directory and we are timing out after 30 seconds.  We will fix this timeout in a futurerelease if that is what you were running into.

**Comment by BigBadBurrow** [comment]
I've just tried updating to latest version of W&B and it seems to work fine now.  So not entirely sure what the issue was, but all's good now.  Thanks.
