### ISSUE TITLE
Wandb across multiple notebooks

### ISSUE THREAD

**Issue by rjdoubleu** [wandb/client#754]
* wandb, version 0.8.19
* Python 3.6.9
* Linux (Google Colab)

### Description

I am trying to use the wandb.log function across multiple notebooks. I have already [modified](https://medium.com/@ryanwalden/how-to-use-papermill-in-google-colab-9f83df1dcb70) my Google Colab notebooks such that they will work with papermill and scrapbook. 

### What I Did
The way that seemed clearest to do this was to initialize a wandb session with `resume=True` (let's call this Notebook 1 ) then call another notebook (Notebook 2) with papermill from Notebook 1, and parameterize it to initialize a wandb session with the same project name. This results instead in creating another run folder in the wandb directory with a similar name:

`run-20200110_185809-6dfv5i6p`
`run-20200110_185900-6dfv5i6p`
 
I also saw the documentation for grouping in wandb but I'd rather keep all notebooks I call with papermill reporting to the same run.

Notebook 1 Initialization and Papermill:
```
session = wandb.init(project="p_name", entity="company", name="ABC, magic=True, resume=True)
parameters = {}
parameters['project_name'] = session.name

output_nb = pm.execute_notebook(
        input_path = "Notebook 2.ipynb",
        output_path = "Notebook 2 Out.ipynb", 
        parameters = parameters
    )
```

Notebook 2 Initialization:
```
project_name = None # this will be updated by the papermill parameters
wandb.init(project=project_name, resume=True)
```

**Comment by vanpelt** [comment]
Hey @rjdoubleu I need to understand more about what each notebook is doing.  Are you actually resuming from a checkpoint in the other notebook?  The multiple run directories is actually intentional, they still should report metrics to the same run in the wandb backend.

`resume=True` likely won't work correctly in a notebook context.  It writes a file with the current run_id and removes it when a program successfully exits.  The use case was meant for cases where your program might crash and you want to resume from a checkpoint on the same machine.  You can also manually specify a unique id with the `id` parameter, this removes the requirement that each process shares the same file system.  There's a helper to generate the id with `wandb.util.generate_id()`

**Comment by rjdoubleu** [comment]
In simplest terms, I would like to log new data to the same run with different notebooks. Setting the id in Notebook 1 and passing it to Notebook 2, using it to initialize wandb, resulted in the same new directory issue. My specific use case is the following:

 I have a driver notebook I want to initialize the wandb run with, then a feature engineering notebook which I want to log a plot from to the same run. Ideally I could just used papermill to pass the wandb object from one notebook to the other but papermill does not support object as parameters.

**Comment by rjdoubleu** [comment]
I've actually found the Grouping method to work very well for my use case, thanks for the assistance
