### ISSUE TITLE
Sweep agent unable to call W&B API

### ISSUE THREAD

**Issue by prash-p** [wandb/client#823]
wandb, version 0.8.22
Python 3.6.5
Linux

### Description

I'm running a hyperparameter sweep, and launched an agent which completed 10 runs (I can see them logged successfuly on the sweep page). After the 10 runs the agent started giving the following error:

```
2020-02-02 09:51:54,672 - wandb.wandb_agent - INFO - Running runs: []
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: bad operand type for unary -: 'NoneType'"}
wandb: ERROR  (<Response [500]>)
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: bad operand type for unary -: 'NoneType'"}
wandb: ERROR  (<Response [500]>)
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: bad operand type for unary -: 'NoneType'"}
wandb: ERROR  (<Response [500]>)
```

I stopped the agent and started another one but had the same issue, this time it wasn't able to complete any runs.

**Comment by raubitsj** [comment]
Sorry about that. We are improving the robustness to bad inputs. If you paste the sweep url I can help you diagnose the problem. We should have an update this week or next that better handles whatever you ran into

**Comment by prash-p** [comment]
https://app.wandb.ai/prashant-pand3y/pytorch-unet/sweeps/u3a6gyi8?workspace=user-prashant-pand3y
Thanks

**Comment by raubitsj** [comment]
The problem is that you had a run which didnt log the metric:
https://app.wandb.ai/prashant-pand3y/pytorch-unet/runs/zqew8o9g

We documented this but we intend on fixing it in an upcoming release:
https://docs.wandb.com/sweeps/common-issues

To workaround the issue, make sure you always log the metric you are optimizing when you use bayes search.   You can delete the runs that didn't log the metric and you can restart any agents that stopped.

**Comment by prash-p** [comment]
Hm, that's weird. I don't understand why one of my runs wouldn't log the optimization metric when the previous 8-9 logged them without a problem. Whether that metrics gets logged isn't dependent on any of the hyperparameter choices.
