### ISSUE TITLE
Multiple wandb runs cause steps from different runs to be out of sync 

### ISSUE THREAD

**Issue by TomPyonsuke** [wandb/client#926]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.30
* Python version: 3.5.2
* Operating System: Ubuntu 16.04

### Description

I was trying to create multiple wandb runs and switch back and forth between them to make the updates.

### What I Did

```
import wandb
run = wandb.init(name='aaa', id='1234', project='test3', resume=True, reinit=True)
print(run.step) 
run.log({'x':0.1}, step=0)
print(run.step)
wandb.join()
run = wandb.init(name='aab', id='1235', project='test3', resume=True, reinit=True)
run.log({'x':0.3}, step=0)
print(run.step)
wandb.join()
run = wandb.init(name='aaa', id='1234', project='test3', resume=True, reinit=True)
print(run.step)


```
The expected output above should be 0, 0, 0, 1 but I am getting 0, 0, 0, 2 here. If I increase the number of the runs the behavior becomes even more unpredictable. Is there an issue in how I used the API? I didn't set any environment variables.

**Comment by ayushjaiswal** [comment]
Probably related but when I resume an experiment run and wandb is initialized with resume=True, the _step value does not reflect the expected step index. In my code, I am using wandb.log({'epoch': epoch, 'metric': metric}). In the wandb message I see epoch values being uploaded correctly but the epoch value and the _step value do not match. When I try to visualize on the wandb web UI, there is a clear problem with "step" values, even though the epoch values are correct. Probably related to this, if I try to visualize 'metric' against 'epoch', the points do not get connected with lines for some experiments, but if I visualize 'metric' against 'step', the lines show up but 'step' and 'epoch' do not match, so those plots are useless.

**Comment by kennazilis** [comment]
Hi Tom & Ayush, 
Thank you both for reporting these issues! I have added them to our internal tracker and are taking a look!

**Comment by ayushjaiswal** [comment]
@kennazilis is there any update on this issue? I log `epoch` and `metric` but find that the wandb `_step` does not match with my `epoch` values .

**Comment by vanpelt** [comment]
@ayushjaiswal step will always increment monotonically if it's not specified in `wandb.log`.  You can change any chart to use your custom epoch or other values as x-axis instead of the default _step.

**Comment by ayushjaiswal** [comment]
@vanpelt I am doing that currently. The problem arises when epochs don't get logged in a monotonically increasing fashion. The line plots get messed up as they sort data using the default `_step` instead of `epoch`. Perhaps an additional argument indicating that a particular key (such as `epoch`) is the user's custom `step` variable would be useful? Or maybe having an option on the UI to sort by the X-axis variable when creating line plots? This problem does not arise when a TensorBoard instance is launched.

**Comment by ayushjaiswal** [comment]
@vanpelt is there any update on this?

**Comment by vanpelt** [comment]
@ayushjaiswal so sorry for the delayed response on this.  You can select a custom x-axis in the UI for an individual chart or all charts.

**Comment by meghbhalerao** [comment]
I am also facing a similar issue. I think a simple feature can be added to wandb such that I can simply make different run objects like so - 
```
run1 = wandb.init(id = some_id)
run2 = wandb.init(id = some_id_2)
run3 = wandb.init(id = some_id_3)
```
and then simply keep a step for each of the runs internally so that I can update each of the runs at whatever frequency I want, either epoch wise or iteration wise.

Right now I have tried this but it does not work since it looks like wandb maintains a single global step counter.

This above type of thing would be an extremely useful functionality to have. Right now there is some option to set custom x axis in the python script but that is very convoluted I think - https://docs.wandb.ai/guides/track/log#stepwise-and-incremental-logging
