### ISSUE TITLE
AttributeError: Can't get attribute 'train' on <module '__main__' (built-in)>

### ISSUE THREAD

**Issue by Pavlov228** [wandb/client#956]
`wandb --version && python --version && uname`

* Weights and Biases version: wandb, version 0.8.31
* Python version: Python 3.6.7
* Operating System: Windows 10

### Description

Running tutorial example fails. Link to the tutorial:
https://colab.research.google.com/drive/181GCGp36_75C2zm7WLxr9U2QjMXXoibt

### What I Did

Running tutorial example fails. Link to the tutorial:
https://colab.research.google.com/drive/181GCGp36_75C2zm7WLxr9U2QjMXXoibt

The line with
`wandb.agent(sweep_id, train)`

Gives an error:

```bash
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "c:\users\Admin\appdata\local\programs\python\python36\lib\multiprocessing\spawn.py", line 105, in spawn_main exitcode = _main(fd)
File "c:\users\Admin\appdata\local\programs\python\python36\lib\multiprocessing\spawn.py", line 115, in _main self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'train' on <module '__main__' (built-in)>
```

**Comment by vanpelt** [comment]
Hey @Pavlov228 this is due to the `train` function not being defined.  Did you run the cell that defined `train` before calling `wandb.agent`?

**Comment by Pavlov228** [comment]
@vanpelt This is a really good question, good engineering approach. I definitely ran the cell with `train` function, and `globals()['train']` returns me `<function __main__.train()>`. I hope it is a correct way of checking. Though its a function, not attribute as `pickle` expects.

**Comment by vanpelt** [comment]
Hey @Pavlov228 can you share your colab notebook with vanpelt@wandb.com so I can reproduce?

**Comment by vanpelt** [comment]
Actually, @Pavlov228 I was able to run the notebook and got an error with the tensorflow version.  Which can be fixed by using the colab magic `%tensorflow_version 1.x` before importing tensorflow.

**Comment by nhabbash** [comment]
I've encountered the same error using:

- wandb, version 0.8.32
- Python 3.7.4 (Anaconda)
- Windows 10

I found out that the issue was with Jupyter Notebook (what I was using) not fully supporting multiprocessing. Haven't dug out the details, but a fix that made sweeps work was putting the `train` function definition in an outside .py file, and after that importing it into the notebook.

**Comment by pokey** [comment]
I believe this issue is due to https://github.com/ipython/ipython/issues/10894, which suggests the same workaround as @nhabbash used.

May be a newbie question, but could we run this thing without multiprocessing?  I was hoping not to have to define the `train` function in an outside module because it uses all the variables captured in its closure.

**Comment by ariG23498** [comment]
Hey Folks
Could you check whether this still persists with the latest iteration of our version? Thanks
